import sys
import numpy as np
import pyvista as pv
from pyvistaqt import QtInteractor
from qtpy import QtWidgets, QtCore, QtGui
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

class CAFFADataParser:
    """
    Simulates reading the CAFFA .pos and .out files.
    In a real scenario, use scipy.io.FortranFile to read the binary .pos file
    generated by the POST subroutine.
    """
    @staticmethod
    def read_mesh_and_fields():
        # Mocking the 2D grid generation from CAFFA
        x = np.linspace(0, 10, 50)
        y = np.linspace(0, 5, 25)
        xx, yy = np.meshgrid(x, y)
        z = np.zeros_like(xx)
        
        grid = pv.StructuredGrid(xx, yy, z)
        
        # Mocking the fields (U, V, P) from CAFFA post-processing 
        u_vel = np.sin(xx) * np.cos(yy)
        v_vel = -np.cos(xx) * np.sin(yy)
        pressure = xx**2 + yy**2
        
        # Assign to PyVista grid
        grid["Velocity"] = np.c_[u_vel.flatten(), v_vel.flatten(), z.flatten()]
        grid["Pressure"] = pressure.flatten()
        return grid

    @staticmethod
    def read_residuals():
        # Mocking the output of FORMAT 606 (Grid, Cycle, Iter, Residuals) [cite: 25]
        iterations = np.arange(1, 100)
        u_res = np.exp(-iterations / 20.0) + np.random.normal(0, 0.01, 99)
        p_res = np.exp(-iterations / 15.0) + np.random.normal(0, 0.01, 99)
        return iterations, u_res, p_res


class ResidualPlotter(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.layout = QtWidgets.QVBoxLayout(self)
        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)
        self.layout.addWidget(self.canvas)
        self.ax = self.figure.add_subplot(111)
        self.ax.set_title("Residuals")
        self.ax.set_yscale('log')
        self.ax.set_xlabel("Iteration")
        self.ax.set_ylabel("Absolute Residual")

    def update_plot(self, iters, u_res, p_res):
        self.ax.clear()
        self.ax.set_yscale('log')
        self.ax.plot(iters, u_res, label='U-Mom', color='blue')
        self.ax.plot(iters, p_res, label='Mass (P)', color='red')
        self.ax.legend()
        self.ax.grid(True, which="both", ls="--")
        self.canvas.draw()


class StarCaffaWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("CAFFA CFD GUI - Star CCM+ Style")
        self.resize(1200, 800)

        # Main Splitter
        splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.setCentralWidget(splitter)

        # Left Panel: Simulation Tree
        self.tree = QtWidgets.QTreeWidget()
        self.tree.setHeaderLabel("Simulation")
        self._build_tree()
        splitter.addWidget(self.tree)

        # Right Panel: Visualization and Plots
        right_splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        
        # Viewport (PyVista)
        self.plotter = QtInteractor(self)
        right_splitter.addWidget(self.plotter.interactor)
        
        # Residuals Tab
        self.residuals_widget = ResidualPlotter(self)
        right_splitter.addWidget(self.residuals_widget)

        splitter.addWidget(right_splitter)
        splitter.setSizes([300, 900])
        right_splitter.setSizes([600, 200])

        # Load Data
        self.grid = CAFFADataParser.read_mesh_and_fields()
        
        # Connect Tree
        self.tree.itemClicked.connect(self.handle_tree_click)

    def _build_tree(self):
        nodes = ["Geometry", "Continua", "Physics", "Solvers", "Scenes", "Plots"]
        for node in nodes:
            parent = QtWidgets.QTreeWidgetItem(self.tree, [node])
            if node == "Scenes":
                QtWidgets.QTreeWidgetItem(parent, ["Pressure Contour"])
                QtWidgets.QTreeWidgetItem(parent, ["Velocity Magnitude"])
                QtWidgets.QTreeWidgetItem(parent, ["Vector Scene"])
            elif node == "Plots":
                QtWidgets.QTreeWidgetItem(parent, ["Residuals"])
        self.tree.expandAll()

    def handle_tree_click(self, item, column):
        name = item.text(0)
        self.plotter.clear()
        
        if name == "Pressure Contour":
            self.plotter.add_mesh(self.grid, scalars="Pressure", cmap="jet", show_scalar_bar=True)
            self.plotter.add_text("Pressure (Pa)", font_size=10)
            self.plotter.view_xy()
            
        elif name == "Velocity Magnitude":
            # Compute magnitude
            mag = np.linalg.norm(self.grid["Velocity"], axis=1)
            self.grid["Velocity_Mag"] = mag
            self.plotter.add_mesh(self.grid, scalars="Velocity_Mag", cmap="viridis")
            self.plotter.add_text("Velocity Magnitude", font_size=10)
            self.plotter.view_xy()
            
        elif name == "Vector Scene":
            # Use glyphs for vectors
            self.plotter.add_mesh(self.grid.outline(), color="black")
            glyphs = self.grid.glyph(orient="Velocity", scale="Velocity", factor=0.5)
            self.plotter.add_mesh(glyphs, scalars="Velocity_Mag", cmap="turbo")
            self.plotter.add_text("Velocity Vectors", font_size=10)
            self.plotter.view_xy()
            
        elif name == "Residuals":
            iters, u, p = CAFFADataParser.read_residuals()
            self.residuals_widget.update_plot(iters, u, p)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = StarCaffaWindow()
    window.show()
    sys.exit(app.exec_())