# -*- coding: utf-8 -*-
"""OpenFOAM GUI (STAR-CCM+ Style)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBjaxcZfcVl-8UViXnfGVXPvJW2PWUEa
"""

import sys
import os
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, QTreeView,
    QStackedWidget, QLabel, QLineEdit, QPushButton, QFormLayout, QTextEdit,
    QFileDialog, QMessageBox, QSplitter, QGroupBox, QComboBox, QDoubleSpinBox,
    QSpinBox, QCheckBox, QSizePolicy
)
from PyQt6.QtGui import QStandardItemModel, QStandardItem, QIcon, QAction, QFont
from PyQt6.QtCore import Qt, QSize

class OpenFOAMStarApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("OpenFOAM Case Manager (STAR-CCM+ Style)")
        self.setGeometry(50, 50, 1600, 900)

        self.current_case_path = None
        self.property_widgets = {} # To store references to property input widgets

        self._create_actions()
        self._create_menu_bar()
        self._create_tool_bar() # Basic toolbar
        self._init_ui()

        self.statusBar().showMessage("Ready. Create or open an OpenFOAM case.")

    def _create_actions(self):
        # File Actions
        self.new_case_action = QAction(QIcon.fromTheme("document-new", QIcon("icons/new.png")), "&New Case...", self)
        self.new_case_action.triggered.connect(self.new_case)
        self.open_case_action = QAction(QIcon.fromTheme("document-open", QIcon("icons/open.png")), "&Open Case...", self)
        self.open_case_action.triggered.connect(self.open_case)
        self.save_action = QAction(QIcon.fromTheme("document-save", QIcon("icons/save.png")), "&Save Configuration", self)
        self.save_action.triggered.connect(self.save_configuration) # Placeholder
        self.save_action.setEnabled(False) # Enable when a case is active
        self.exit_action = QAction(QIcon.fromTheme("application-exit"), "E&xit", self)
        self.exit_action.triggered.connect(self.close)

        # Run Actions (Placeholders)
        self.run_blockmesh_action = QAction(QIcon("icons/run_blockmesh.png"), "Run blockMesh", self) # Add icons later
        self.run_blockmesh_action.triggered.connect(lambda: self.run_utility("blockMesh"))
        self.run_snappyhexmesh_action = QAction(QIcon("icons/run_snappy.png"), "Run snappyHexMesh", self)
        self.run_snappyhexmesh_action.triggered.connect(lambda: self.run_utility("snappyHexMesh"))
        self.run_solver_action = QAction(QIcon("icons/run_solver.png"), "Run Solver", self)
        self.run_solver_action.triggered.connect(self.run_solver)

        # Initially disable run actions
        self.run_blockmesh_action.setEnabled(False)
        self.run_snappyhexmesh_action.setEnabled(False)
        self.run_solver_action.setEnabled(False)


    def _create_menu_bar(self):
        menu_bar = self.menuBar()
        # File Menu
        file_menu = menu_bar.addMenu("&File")
        file_menu.addAction(self.new_case_action)
        file_menu.addAction(self.open_case_action)
        file_menu.addAction(self.save_action)
        file_menu.addSeparator()
        file_menu.addAction(self.exit_action)

        # Run Menu
        run_menu = menu_bar.addMenu("&Run")
        run_menu.addAction(self.run_blockmesh_action)
        run_menu.addAction(self.run_snappyhexmesh_action)
        run_menu.addSeparator()
        run_menu.addAction(self.run_solver_action)

        # View Menu (Placeholder)
        view_menu = menu_bar.addMenu("&View")
        # ... add view options like show/hide panels

    def _create_tool_bar(self):
        toolbar = self.addToolBar("Main Toolbar")
        toolbar.setIconSize(QSize(24,24)) # Adjust icon size
        toolbar.addAction(self.new_case_action)
        toolbar.addAction(self.open_case_action)
        toolbar.addAction(self.save_action)
        toolbar.addSeparator()
        toolbar.addAction(self.run_blockmesh_action)
        toolbar.addAction(self.run_snappyhexmesh_action)
        toolbar.addAction(self.run_solver_action)


    def _init_ui(self):
        # Main widget and layout
        main_widget = QWidget()
        self.setCentralWidget(main_widget)
        main_layout = QHBoxLayout(main_widget)

        # --- Left Panel: Tree Navigator ---
        self.tree_view = QTreeView()
        self.tree_model = QStandardItemModel()
        self.tree_view.setModel(self.tree_model)
        self.tree_view.setHeaderHidden(True)
        self.tree_view.setFixedWidth(250) # Typical width for a tree navigator
        self.tree_view.clicked.connect(self.on_tree_item_clicked)
        self.populate_tree() # Initial empty/default tree

        # --- Central Area (Splitter for Graphics and Console) ---
        central_splitter = QSplitter(Qt.Orientation.Vertical)

        # Placeholder for Graphics/Main Content View
        self.graphics_view_placeholder = QLabel("Graphics View (Placeholder)")
        self.graphics_view_placeholder.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graphics_view_placeholder.setFont(QFont("Arial", 16))
        self.graphics_view_placeholder.setStyleSheet("background-color: #333; color: #ccc; border: 1px solid #555;")
        central_splitter.addWidget(self.graphics_view_placeholder)

        # Console Output Area
        self.console_output = QTextEdit()
        self.console_output.setReadOnly(True)
        self.console_output.setFontFamily("monospace")
        self.console_output.setStyleSheet("background-color: #1e1e1e; color: #d4d4d4; border: 1px solid #555;")
        self.console_output.setMinimumHeight(150)
        central_splitter.addWidget(self.console_output)
        central_splitter.setStretchFactor(0, 3) # Graphics view takes more space
        central_splitter.setStretchFactor(1, 1)

        # --- Right Panel: Properties Editor ---
        self.properties_stack = QStackedWidget()
        self.properties_stack.setFixedWidth(350) # Typical width for properties
        self.create_property_panels()

        # --- Main Splitter for Tree, Central, Properties ---
        main_splitter = QSplitter(Qt.Orientation.Horizontal)
        main_splitter.addWidget(self.tree_view)
        main_splitter.addWidget(central_splitter) # Add the central splitter here
        main_splitter.addWidget(self.properties_stack)

        main_splitter.setStretchFactor(0, 0) # Tree view fixed width (set above)
        main_splitter.setStretchFactor(1, 1) # Central area takes available space
        main_splitter.setStretchFactor(2, 0) # Properties fixed width (set above)

        main_layout.addWidget(main_splitter)

    def populate_tree(self, case_name="Untitled Case"):
        self.tree_model.clear()
        root_node = self.tree_model.invisibleRootItem()

        case_item = QStandardItem(case_name)
        case_item.setData("case_info", Qt.ItemDataRole.UserRole) # Custom data to identify panel
        root_node.appendRow(case_item)

        # Geometry
        geom_item = QStandardItem("Geometry")
        geom_item.setData("geometry_setup", Qt.ItemDataRole.UserRole)
        case_item.appendRow(geom_item)
        # geom_files_item = QStandardItem("Surface Files (.stl, .obj)")
        # geom_files_item.setData("geometry_files", Qt.ItemDataRole.UserRole)
        # geom_item.appendRow(geom_files_item)


        # Meshing
        meshing_item = QStandardItem("Meshing")
        meshing_item.setData("meshing_overview", Qt.ItemDataRole.UserRole)
        case_item.appendRow(meshing_item)

        bm_item = QStandardItem("blockMesh")
        bm_item.setData("blockMesh_settings", Qt.ItemDataRole.UserRole)
        meshing_item.appendRow(bm_item)

        shm_item = QStandardItem("snappyHexMesh")
        shm_item.setData("snappyHexMesh_settings", Qt.ItemDataRole.UserRole)
        meshing_item.appendRow(shm_item)

        # Physics Models
        physics_item = QStandardItem("Physics Models")
        physics_item.setData("physics_overview", Qt.ItemDataRole.UserRole)
        case_item.appendRow(physics_item)
        # transport_item = QStandardItem("Transport Properties")
        # transport_item.setData("transport_properties", Qt.ItemDataRole.UserRole)
        # physics_item.appendRow(transport_item)
        # turbulence_item = QStandardItem("Turbulence Model")
        # turbulence_item.setData("turbulence_model", Qt.ItemDataRole.UserRole)
        # physics_item.appendRow(turbulence_item)


        # Boundary Conditions
        bcs_item = QStandardItem("Boundary Conditions")
        bcs_item.setData("boundary_conditions_overview", Qt.ItemDataRole.UserRole)
        case_item.appendRow(bcs_item)

        # Solver Settings
        solvers_item = QStandardItem("Solver Settings")
        solvers_item.setData("solver_settings_overview", Qt.ItemDataRole.UserRole)
        case_item.appendRow(solvers_item)

        control_dict_item = QStandardItem("Control (controlDict)")
        control_dict_item.setData("controlDict_settings", Qt.ItemDataRole.UserRole) # Key for panel
        solvers_item.appendRow(control_dict_item)

        fv_schemes_item = QStandardItem("Schemes (fvSchemes)")
        fv_schemes_item.setData("fvSchemes_settings", Qt.ItemDataRole.UserRole)
        solvers_item.appendRow(fv_schemes_item)

        fv_solution_item = QStandardItem("Solution (fvSolution)")
        fv_solution_item.setData("fvSolution_settings", Qt.ItemDataRole.UserRole)
        solvers_item.appendRow(fv_solution_item)

        # Solution
        solution_item = QStandardItem("Solution")
        solution_item.setData("solution_overview", Qt.ItemDataRole.UserRole)
        case_item.appendRow(solution_item)
        # run_control_item = QStandardItem("Run Control")
        # run_control_item.setData("run_control", Qt.ItemDataRole.UserRole)
        # solution_item.appendRow(run_control_item)
        # function_objects_item = QStandardItem("Function Objects")
        # function_objects_item.setData("function_objects", Qt.ItemDataRole.UserRole)
        # solution_item.appendRow(function_objects_item)

        self.tree_view.expandAll()


    def create_property_panels(self):
        # Default/Welcome Panel
        welcome_panel = QWidget()
        welcome_layout = QVBoxLayout(welcome_panel)
        welcome_label = QLabel("Select an item from the tree to edit its properties.")
        welcome_label.setWordWrap(True)
        welcome_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        welcome_layout.addWidget(welcome_label)
        self.properties_stack.addWidget(welcome_panel)
        self.property_panel_map = {"default": 0} # Map item data to stack index

        # Case Info Panel
        case_info_panel = QWidget()
        case_info_layout = QFormLayout(case_info_panel)
        self.prop_case_path_label = QLabel("N/A")
        self.prop_case_path_label.setWordWrap(True)
        self.prop_btn_set_case_path = QPushButton("Set/Change Case Path...")
        self.prop_btn_set_case_path.clicked.connect(self.set_case_path_dialog)
        case_info_layout.addRow("Current Case Path:", self.prop_case_path_label)
        case_info_layout.addRow(self.prop_btn_set_case_path)
        self.properties_stack.addWidget(case_info_panel)
        self.property_panel_map["case_info"] = self.properties_stack.count() - 1

        # controlDict Panel
        cd_panel = QWidget()
        cd_layout = QFormLayout(cd_panel)
        cd_panel.setLayout(cd_layout)

        self.property_widgets["cd_solver"] = QLineEdit("icoFoam")
        self.property_widgets["cd_startTime"] = QDoubleSpinBox(value=0.0)
        self.property_widgets["cd_endTime"] = QDoubleSpinBox(value=1.0)
        self.property_widgets["cd_deltaT"] = QDoubleSpinBox(value=0.005)
        self.property_widgets["cd_writeControl"] = QComboBox()
        self.property_widgets["cd_writeControl"].addItems(["timeStep", "runTime", "adjustableRunTime", "cpuTime", "clockTime"])
        self.property_widgets["cd_writeInterval"] = QDoubleSpinBox(value=0.1)
        self.property_widgets["cd_purgeWrite"] = QSpinBox(value=0) # Integer
        self.property_widgets["cd_writeFormat"] = QComboBox()
        self.property_widgets["cd_writeFormat"].addItems(["ascii", "binary"])
        self.property_widgets["cd_writeCompression"] = QCheckBox("Compressed")
        self.property_widgets["cd_timeFormat"] = QComboBox()
        self.property_widgets["cd_timeFormat"].addItems(["general", "fixed", "scientific"])
        self.property_widgets["cd_timePrecision"] = QSpinBox(value=6)

        for w in [self.property_widgets["cd_startTime"], self.property_widgets["cd_endTime"],
                  self.property_widgets["cd_deltaT"], self.property_widgets["cd_writeInterval"]]:
            w.setDecimals(6) # For time/dt values
            w.setSingleStep(0.001)
            w.setRange(-1e9, 1e9) # Wide range

        cd_layout.addRow("application:", self.property_widgets["cd_solver"])
        cd_layout.addRow("startTime:", self.property_widgets["cd_startTime"])
        cd_layout.addRow("endTime:", self.property_widgets["cd_endTime"])
        cd_layout.addRow("deltaT:", self.property_widgets["cd_deltaT"])
        cd_layout.addRow("writeControl:", self.property_widgets["cd_writeControl"])
        cd_layout.addRow("writeInterval:", self.property_widgets["cd_writeInterval"])
        cd_layout.addRow("purgeWrite:", self.property_widgets["cd_purgeWrite"])
        cd_layout.addRow("writeFormat:", self.property_widgets["cd_writeFormat"])
        cd_layout.addRow("writeCompression:", self.property_widgets["cd_writeCompression"])
        cd_layout.addRow("timeFormat:", self.property_widgets["cd_timeFormat"])
        cd_layout.addRow("timePrecision:", self.property_widgets["cd_timePrecision"])

        btn_save_cd = QPushButton("Save controlDict")
        btn_save_cd.clicked.connect(self.save_control_dict)
        cd_layout.addRow(btn_save_cd)

        self.properties_stack.addWidget(cd_panel)
        self.property_panel_map["controlDict_settings"] = self.properties_stack.count() - 1

        # Placeholder panels for other items
        for item_key in ["geometry_setup", "meshing_overview", "blockMesh_settings",
                         "snappyHexMesh_settings", "physics_overview", "boundary_conditions_overview",
                         "solver_settings_overview", "fvSchemes_settings", "fvSolution_settings",
                         "solution_overview"]:
            panel = QWidget()
            layout = QVBoxLayout(panel)
            label_text = item_key.replace("_", " ").title() + " Panel"
            layout.addWidget(QLabel(f"Settings for: {label_text}\n(Not Implemented Yet)"))
            self.properties_stack.addWidget(panel)
            self.property_panel_map[item_key] = self.properties_stack.count() - 1


    def on_tree_item_clicked(self, index):
        item = self.tree_model.itemFromIndex(index)
        if item:
            item_data_key = item.data(Qt.ItemDataRole.UserRole)
            if item_data_key in self.property_panel_map:
                self.properties_stack.setCurrentIndex(self.property_panel_map[item_data_key])
                self.statusBar().showMessage(f"Selected: {item.text()}")
                if item_data_key == "controlDict_settings":
                    self.load_control_dict_to_gui() # Attempt to load if case path exists
            else:
                self.properties_stack.setCurrentIndex(self.property_panel_map["default"])
                self.statusBar().showMessage(f"Selected: {item.text()} (No specific panel)")


    def new_case(self):
        path = QFileDialog.getSaveFileName(self, "Create New OpenFOAM Case Directory", "", "Directory")
        if path[0]:
            self.current_case_path = path[0]
            try:
                if not os.path.exists(self.current_case_path):
                    os.makedirs(self.current_case_path)
                # Create basic structure
                os.makedirs(os.path.join(self.current_case_path, "0"), exist_ok=True)
                os.makedirs(os.path.join(self.current_case_path, "constant"), exist_ok=True)
                os.makedirs(os.path.join(self.current_case_path, "system"), exist_ok=True)

                self.prop_case_path_label.setText(self.current_case_path)
                self.populate_tree(os.path.basename(self.current_case_path))
                self.log_message(f"Created and set new case path: {self.current_case_path}")
                self.update_run_actions_state(True)
                self.save_action.setEnabled(True)
                # Create a default controlDict
                self.save_control_dict(is_new_case=True)

            except Exception as e:
                QMessageBox.critical(self, "Error Creating Case", f"Could not create case directory or structure: {e}")
                self.log_message(f"Error: {e}")
                self.current_case_path = None

    def open_case(self):
        path = QFileDialog.getExistingDirectory(self, "Open OpenFOAM Case Directory")
        if path:
            # Basic check for OpenFOAM structure (can be improved)
            if os.path.isdir(os.path.join(path, "system")) and \
               os.path.isdir(os.path.join(path, "constant")):
                self.current_case_path = path
                self.prop_case_path_label.setText(self.current_case_path)
                self.populate_tree(os.path.basename(self.current_case_path))
                self.log_message(f"Opened case: {self.current_case_path}")
                self.load_control_dict_to_gui()
                self.update_run_actions_state(True)
                self.save_action.setEnabled(True)
            else:
                QMessageBox.warning(self, "Invalid Case", "The selected directory does not appear to be a valid OpenFOAM case (missing system/constant folders).")
                self.log_message("Failed to open invalid case directory.")

    def set_case_path_dialog(self):
        # This could be merged with open_case or provide more options
        self.open_case()

    def save_configuration(self):
        # This would save the GUI's internal state or settings related to the case,
        # not necessarily all OpenFOAM files unless explicitly triggered.
        if not self.current_case_path:
            QMessageBox.warning(self, "No Case", "No active case to save configuration for.")
            return
        # Example: Save controlDict if its panel is active or dirty
        # self.save_control_dict()
        self.log_message("Case configuration saved (placeholder).")
        QMessageBox.information(self, "Save Configuration", "Configuration saved (placeholder functionality).")

    def log_message(self, message):
        self.console_output.append(message)

    def update_run_actions_state(self, enabled):
        self.run_blockmesh_action.setEnabled(enabled)
        self.run_snappyhexmesh_action.setEnabled(enabled)
        self.run_solver_action.setEnabled(enabled)

    # --- controlDict Specific Methods ---
    def load_control_dict_to_gui(self):
        if not self.current_case_path:
            return

        cd_path = os.path.join(self.current_case_path, "system", "controlDict")
        if not os.path.exists(cd_path):
            self.log_message(f"controlDict not found at {cd_path}. Using default GUI values.")
            # Reset to default if file not found, or keep current GUI values?
            # For now, we assume save_control_dict would create it if it's a new case.
            return

        try:
            with open(cd_path, 'r') as f:
                content = f.read()

            # Basic parsing (can be made much more robust with pyparsing or regex)
            def find_val(key):
                import re
                match = re.search(rf"^\s*{key}\s+([^;]+);", content, re.MULTILINE)
                return match.group(1).strip() if match else None

            self.property_widgets["cd_solver"].setText(find_val("application") or "icoFoam")
            self.property_widgets["cd_startTime"].setValue(float(find_val("startTime") or 0.0))
            self.property_widgets["cd_endTime"].setValue(float(find_val("endTime") or 1.0))
            self.property_widgets["cd_deltaT"].setValue(float(find_val("deltaT") or 0.005))
            self.property_widgets["cd_writeControl"].setCurrentText(find_val("writeControl") or "timeStep")
            self.property_widgets["cd_writeInterval"].setValue(float(find_val("writeInterval") or 0.1))
            self.property_widgets["cd_purgeWrite"].setValue(int(find_val("purgeWrite") or 0))
            self.property_widgets["cd_writeFormat"].setCurrentText(find_val("writeFormat") or "ascii")
            self.property_widgets["cd_writeCompression"].setChecked((find_val("writeCompression") or "off") == "on")
            self.property_widgets["cd_timeFormat"].setCurrentText(find_val("timeFormat") or "general")
            self.property_widgets["cd_timePrecision"].setValue(int(find_val("timePrecision") or 6))
            self.log_message(f"Loaded controlDict settings from {cd_path}")

        except Exception as e:
            self.log_message(f"Error loading controlDict: {e}")
            QMessageBox.warning(self, "Load Error", f"Could not fully parse controlDict: {e}")

    def save_control_dict(self, is_new_case=False):
        if not self.current_case_path:
            if not is_new_case: # Allow saving if it's part of new case creation
                QMessageBox.warning(self, "No Case", "No active case path set to save controlDict.")
                return
            # If is_new_case is true but current_case_path is still None, something is wrong.
            # This should be handled by the new_case logic ensuring current_case_path is set.

        system_dir = os.path.join(self.current_case_path, "system")
        os.makedirs(system_dir, exist_ok=True)
        cd_path = os.path.join(system_dir, "controlDict")

        content = f"""/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  v2312 (example)                       |
|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      {self.property_widgets['cd_writeFormat'].currentText()};
    class       dictionary;
    location    "system";
    object      controlDict;
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

application     {self.property_widgets['cd_solver'].text()};

startFrom       startTime;
startTime       {self.property_widgets['cd_startTime'].value()};
stopAt          endTime;
endTime         {self.property_widgets['cd_endTime'].value()};
deltaT          {self.property_widgets['cd_deltaT'].value()};

writeControl    {self.property_widgets['cd_writeControl'].currentText()};
writeInterval   {self.property_widgets['cd_writeInterval'].value()};
purgeWrite      {self.property_widgets['cd_purgeWrite'].value()};
writeFormat     {self.property_widgets['cd_writeFormat'].currentText()};
writePrecision  6; // Not in GUI yet, hardcoded
writeCompression { 'on' if self.property_widgets['cd_writeCompression'].isChecked() else 'off' };

timeFormat      {self.property_widgets['cd_timeFormat'].currentText()};
timePrecision   {self.property_widgets['cd_timePrecision'].value()};

// runTimeModifiable true; // Not in GUI yet

// functions {{ ... }} // Not in GUI yet

// ************************************************************************* //
"""
        try:
            with open(cd_path, 'w') as f:
                f.write(content)
            self.log_message(f"controlDict saved to {cd_path}")
            if not is_new_case: # Don't show popup if it's part of new case creation
                 QMessageBox.information(self, "Saved", "controlDict saved successfully.")
        except Exception as e:
            self.log_message(f"Error saving controlDict: {e}")
            QMessageBox.critical(self, "Save Error", f"Could not save controlDict: {e}")

    # --- Placeholder Run Methods ---
    def run_utility(self, utility_name):
        if not self.current_case_path:
            QMessageBox.warning(self, "No Case", "No active case selected.")
            return
        self.log_message(f"Running {utility_name} in {self.current_case_path} (simulation - not actually running command).")
        # In a real app, you would use subprocess to run the command:
        # import subprocess
        # process = subprocess.Popen([utility_name], cwd=self.current_case_path,
        #                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        # stdout, stderr = process.communicate()
        # self.log_message(f"{utility_name} stdout:\n{stdout}")
        # if stderr: self.log_message(f"{utility_name} stderr:\n{stderr}")
        QMessageBox.information(self, "Run Utility", f"Simulated running {utility_name}. Check console log.")

    def run_solver(self):
        if not self.current_case_path:
            QMessageBox.warning(self, "No Case", "No active case selected.")
            return
        solver_app = self.property_widgets["cd_solver"].text() # Get solver from controlDict GUI
        self.log_message(f"Running solver {solver_app} in {self.current_case_path} (simulation).")
        QMessageBox.information(self, "Run Solver", f"Simulated running solver {solver_app}. Check console log.")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # You can set a global style if desired: app.setStyleSheet(...)
    # For icons, create an 'icons' folder next to your script or use system theme icons.
    # Example: QIcon.fromTheme("document-new") for system icons.
    # For custom icons, ensure the paths are correct (e.g., "icons/new.png")

    # A simple style to make it look a bit more "engineered"
    app.setStyleSheet("""
        QMainWindow, QWidget {
            background-color: #4a4a4a; /* Darker gray background */
            color: #e0e0e0; /* Light gray text */
        }
        QTreeView {
            background-color: #555555;
            border: 1px solid #6a6a6a;
            alternate-background-color: #5d5d5d; /* For item rows if enabled */
        }
        QTreeView::item:selected {
            background-color: #0078d7; /* Blue selection like many modern apps */
            color: white;
        }
        QStackedWidget > QWidget { /* Target children of QStackedWidget */
            background-color: #505050; /* Slightly different for property panels */
        }
        QLabel {
            color: #e0e0e0;
        }
        QLineEdit, QComboBox, QDoubleSpinBox, QSpinBox {
            background-color: #3d3d3d;
            color: #e0e0e0;
            border: 1px solid #6a6a6a;
            padding: 3px;
            min-height: 20px;
        }
        QLineEdit:focus, QComboBox:focus, QDoubleSpinBox:focus, QSpinBox:focus {
            border: 1px solid #0078d7;
        }
        QPushButton {
            background-color: #636363;
            color: #e0e0e0;
            border: 1px solid #7a7a7a;
            padding: 5px 10px;
            min-height: 22px;
        }
        QPushButton:hover {
            background-color: #707070;
        }
        QPushButton:pressed {
            background-color: #585858;
        }
        QTextEdit { /* Console */
            background-color: #252526;
            color: #cccccc;
            border: 1px solid #3f3f46;
            font-family: Consolas, Courier New, monospace;
        }
        QMenuBar {
            background-color: #404040;
            color: #e0e0e0;
        }
        QMenuBar::item:selected {
            background-color: #0078d7;
        }
        QMenu {
            background-color: #404040;
            color: #e0e0e0;
            border: 1px solid #555555;
        }
        QMenu::item:selected {
            background-color: #0078d7;
        }
        QToolBar {
            background-color: #404040;
            border: none;
            padding: 2px;
        }
        QToolBar QToolButton {
            color: #e0e0e0;
            padding: 3px;
        }
        QToolBar QToolButton:hover {
            background-color: #585858;
        }
        QToolBar QToolButton:pressed {
            background-color: #0078d7;
        }
        QStatusBar {
            color: #e0e0e0;
        }
        QSplitter::handle {
            background-color: #5a5a5a;
        }
        QSplitter::handle:horizontal {
            width: 2px;
        }
        QSplitter::handle:vertical {
            height: 2px;
        }
    """)
    main_window = OpenFOAMStarApp()
    main_window.show()
    sys.exit(app.exec())