# -*- coding: utf-8 -*-
"""PyQt6 snappyHexMeshDict Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ndj3XxXdRS978HRpmkACX11TMCYXRxv
"""

import sys
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QTabWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QFormLayout, QLineEdit, QPushButton, QTableWidget, QTableWidgetItem,
    QComboBox, QMessageBox, QTextEdit, QFileDialog, QLabel, QHeaderView,
    QSpinBox, QDoubleSpinBox, QCheckBox, QScrollArea
)
from PyQt5.QtCore import Qt, QRegularExpression
from PyQt5.QtGui import QRegularExpressionValidator, QFont

class SnappyHexMeshApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("PyQt snappyHexMeshDict Generator (ICEM Style)")
        self.setGeometry(50, 50, 1400, 900) # Increased size for more content

        # --- Data Storage ---
        # General
        self.general_settings = {
            "castellatedMesh": True,
            "snap": True,
            "addLayers": True,
            "convertToMeters": 1.0,
            "mergeTolerance": 1e-6
        }
        self.geometries = []  # List of dicts: {"name": "", "type": "", "file": "", "regions": ""}

        # CastellatedMeshControls
        self.castellated_mesh_controls = {
            "maxLocalCells": 1000000,
            "maxGlobalCells": 2000000,
            "minRefinementCells": 0, # Typically 0 or 10
            "maxLoadUnbalance": 0.10,
            "nCellsBetweenLevels": 3,
            "locationInMesh": [0.0, 0.0, 0.0], # x, y, z
            "allowFreeStandingZoneFaces": True,
            "features": [], # List of dicts: {"file": "", "level": 0}
            "refinementSurfaces": [], # List of dicts: {"geometry": "", "level_min": 1, "level_max": 2, "regions": "", "patchInfo": ""}
            "refinementRegions": [] # List of dicts: {"geometry": "", "mode": "inside", "levels": "1.0 1; 0.5 2"}
        }

        # SnapControls
        self.snap_controls = {
            "nSmoothPatch": 3,
            "tolerance": 2.0,
            "nSolveIter": 30,
            "nRelaxIter": 5,
            "nFeatureSnapIter": 10, # Often matches nRelaxIter or is more
            "implicitFeatureSnap": True,
            "explicitFeatureSnap": False, # Usually false if implicit is true
            "multiRegionFeatureSnap": False
        }

        # AddLayersControls
        self.add_layers_controls = {
            "relativeSizes": True,
            "expansionRatio": 1.2,
            "finalLayerThickness": 0.3,
            "minThickness": 0.1,
            "nGrow": 0,
            "featureAngle": 120.0, # degrees, OpenFOAM default is 30, but higher often used
            "maxFaceThicknessRatio": 0.5,
            "nSmoothSurfaceNormals": 1,
            "nSmoothThickness": 10,
            "slipFeatureAngle": 30.0,
            "nBufferCellsNoExtrude": 0,
            "nLayerIter": 50,
            "layers": [] # List of dicts: {"patchName": "", "nSurfaceLayers": 3}
        }

        # MeshQualityControls
        self.mesh_quality_controls = {
            "maxNonOrtho": 65.0,
            "maxBoundarySkewness": 20.0,
            "maxInternalSkewness": 4.0,
            "maxConcave": 80.0,
            "minFlatness": 0.5, # Not a standard SHM control, usually minFaceFlatness or similar
            "minVol": 1e-13,
            "minTetQuality": 1e-9, # Default 1e-30, but often increased
            "minArea": -1.0, # Disabled by default
            "minTwist": 0.02,
            "minDeterminant": 0.001,
            "minFaceWeight": 0.05,
            "minVolRatio": 0.01,
            "minTriangleTwist": -1.0, # Disabled
            "nSmoothScale": 4,
            "errorReduction": 0.75,
            "relaxed": { # Optional sub-dictionary
                "enabled": False,
                "maxNonOrtho": 75.0
            }
        }

        self.debug_flags = []
        self.write_flags = []


        self.init_ui()

    def init_ui(self):
        self.tabs = QTabWidget()
        self.setCentralWidget(self.tabs)

        self.create_general_geometry_tab()
        self.create_castellated_mesh_tab()
        self.create_snap_controls_tab()
        self.create_add_layers_tab()
        self.create_mesh_quality_tab()
        self.create_advanced_output_tab()
        self.create_generate_tab()

        self.tabs.currentChanged.connect(self.on_tab_change)


        self.statusBar().showMessage("Ready")

    def create_scrollable_tab(self):
        """Helper to create a tab with a scroll area for many widgets."""
        tab_content_widget = QWidget()
        main_layout = QVBoxLayout(tab_content_widget) # This will hold the actual content

        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setWidget(tab_content_widget)

        return scroll_area, main_layout # Return the scroll area to add to tabs, and layout to add content to

    def get_defined_geometry_names(self):
        return [g["name"] for g in self.geometries if g["name"]]

    def get_potential_patch_names(self):
        """Collects geometry names and regions as potential patch names."""
        names = set()
        for geo in self.geometries:
            if geo["name"]:
                names.add(geo["name"]) # The geometry itself can be a patch
            if geo["regions"]:
                # Assuming regions are comma-separated
                regions = [r.strip() for r in geo["regions"].split(',') if r.strip()]
                for region_name in regions:
                    # Often regions are named like "geomName.regionName" or just "regionName"
                    # For simplicity, we'll just add the region name.
                    # User needs to ensure these match how SHM interprets them.
                    names.add(region_name)
        return sorted(list(names)) if names else ["DefaultPatch"]


    def on_tab_change(self, index):
        """Called when tab is changed, to update dynamic elements like ComboBoxes."""
        if self.tabs.tabText(index) == "2. Castellated Mesh":
            self.update_castellated_geometry_combos()
        elif self.tabs.tabText(index) == "4. Add Layers":
            self.update_add_layers_patch_combos()


    # --- Tab 1: General & Geometry ---
    def create_general_geometry_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()

        # General Booleans
        general_group = QWidget()
        general_layout = QFormLayout(general_group)
        general_layout.setContentsMargins(10,10,10,10)
        general_layout.setSpacing(10)

        self.cb_castellated = QCheckBox("Run Castellated Meshing Phase")
        self.cb_castellated.setChecked(self.general_settings["castellatedMesh"])
        general_layout.addRow(self.cb_castellated)

        self.cb_snap = QCheckBox("Run Snapping Phase")
        self.cb_snap.setChecked(self.general_settings["snap"])
        general_layout.addRow(self.cb_snap)

        self.cb_add_layers = QCheckBox("Run Add Layers Phase")
        self.cb_add_layers.setChecked(self.general_settings["addLayers"])
        general_layout.addRow(self.cb_add_layers)

        self.le_convert_to_meters = QLineEdit(str(self.general_settings["convertToMeters"]))
        self.le_convert_to_meters.setValidator(QRegularExpressionValidator(QRegularExpression(r"[\d\.]+")))
        general_layout.addRow("convertToMeters:", self.le_convert_to_meters)

        tab_layout.addWidget(QLabel("<h3>General Controls</h3>"))
        tab_layout.addWidget(general_group)
        tab_layout.addSpacing(20)

        # Geometry Section
        geometry_group = QWidget()
        geometry_layout = QVBoxLayout(geometry_group)
        geometry_layout.setContentsMargins(10,10,10,10)

        self.geometry_table = QTableWidget()
        self.geometry_table.setColumnCount(5) # Name, Type, File, Regions, Action
        self.geometry_table.setHorizontalHeaderLabels(["Name*", "Type*", "File Path*", "Regions (opt, comma-sep)", "Action"])
        self.geometry_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.geometry_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Interactive)
        self.geometry_table.setColumnWidth(3, 200)
        self.geometry_table.setColumnWidth(4, 100)


        add_geom_button = QPushButton("Add Geometry Entry")
        add_geom_button.clicked.connect(self.add_geometry_row)

        geometry_layout.addWidget(QLabel("<h3>Input Geometry (STL, OBJ, etc.)</h3>"))
        geometry_layout.addWidget(self.geometry_table)
        geometry_layout.addWidget(add_geom_button)

        tab_layout.addWidget(geometry_group)
        self.tabs.addTab(scroll_area, "1. General & Geometry")
        self.add_geometry_row() # Start with one empty row

    def add_geometry_row(self, data=None):
        row_position = self.geometry_table.rowCount()
        self.geometry_table.insertRow(row_position)

        name_edit = QLineEdit(data["name"] if data else "")

        type_combo = QComboBox()
        type_combo.addItems(["triSurfaceMesh", "extendedFeatureEdgeMesh", "objSurfaceMesh"]) # Common types
        if data: type_combo.setCurrentText(data["type"])

        file_edit = QLineEdit(data["file"] if data else "")
        browse_button = QPushButton("Browse")
        browse_button.clicked.connect(lambda _, r=row_position: self.browse_geometry_file(r))

        file_widget = QWidget()
        file_layout = QHBoxLayout(file_widget)
        file_layout.setContentsMargins(0,0,0,0)
        file_layout.addWidget(file_edit)
        file_layout.addWidget(browse_button)

        regions_edit = QLineEdit(data["regions"] if data else "")

        remove_button = QPushButton("Remove")
        remove_button.clicked.connect(lambda _, r=row_position: self.remove_table_row(self.geometry_table, r, self.geometries))


        self.geometry_table.setCellWidget(row_position, 0, name_edit)
        self.geometry_table.setCellWidget(row_position, 1, type_combo)
        self.geometry_table.setCellWidget(row_position, 2, file_widget)
        self.geometry_table.setCellWidget(row_position, 3, regions_edit)
        self.geometry_table.setCellWidget(row_position, 4, remove_button)

        # Store references if needed, or retrieve data on generation
        # For simplicity, we'll retrieve data when generating the dict

    def browse_geometry_file(self, row):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Geometry File", "", "Geometry Files (*.stl *.obj *.vtk *.eMesh);;All Files (*)")
        if file_path:
            # The file_edit is inside a QWidget which is the cell widget
            file_widget = self.geometry_table.cellWidget(row, 2)
            if file_widget:
                file_edit = file_widget.findChild(QLineEdit)
                if file_edit:
                    file_edit.setText(file_path)

            # Auto-populate name from filename if name is empty
            name_edit = self.geometry_table.cellWidget(row, 0)
            if name_edit and not name_edit.text():
                import os
                base_name = os.path.basename(file_path)
                name_without_ext = os.path.splitext(base_name)[0]
                name_edit.setText(name_without_ext)


    def remove_table_row(self, table, row, data_list=None):
        # This is a generic remover, if data_list is provided, it assumes direct mapping
        # For more complex scenarios, specific logic might be needed
        table.removeRow(row)
        if data_list is not None and 0 <= row < len(data_list):
            del data_list[row]
        # Re-index remove buttons if they rely on row index
        for r in range(table.rowCount()):
            action_widget = table.cellWidget(r, table.columnCount() -1) # Assuming action is last column
            if isinstance(action_widget, QPushButton) and action_widget.text() == "Remove":
                action_widget.disconnect() # Disconnect old slot
                action_widget.clicked.connect(lambda _, current_r=r: self.remove_table_row(table, current_r, data_list))


    # --- Tab 2: Castellated Mesh ---
    def create_castellated_mesh_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()
        cmc = self.castellated_mesh_controls # Alias

        # Basic Parameters
        basic_params_group = QWidget()
        basic_params_layout = QFormLayout(basic_params_group)

        self.cmc_max_local_cells = QSpinBox(value=cmc["maxLocalCells"])
        self.cmc_max_local_cells.setRange(1000, 100000000)
        self.cmc_max_global_cells = QSpinBox(value=cmc["maxGlobalCells"])
        self.cmc_max_global_cells.setRange(1000, 200000000)
        self.cmc_min_ref_cells = QSpinBox(value=cmc["minRefinementCells"])
        self.cmc_min_ref_cells.setRange(0, 100000)
        self.cmc_max_load_unbalance = QDoubleSpinBox(value=cmc["maxLoadUnbalance"])
        self.cmc_max_load_unbalance.setRange(0.01, 1.0); self.cmc_max_load_unbalance.setSingleStep(0.01)
        self.cmc_n_cells_between_levels = QSpinBox(value=cmc["nCellsBetweenLevels"])
        self.cmc_n_cells_between_levels.setRange(1, 10)

        loc_in_mesh_layout = QHBoxLayout()
        self.cmc_loc_x = QLineEdit(str(cmc["locationInMesh"][0]))
        self.cmc_loc_y = QLineEdit(str(cmc["locationInMesh"][1]))
        self.cmc_loc_z = QLineEdit(str(cmc["locationInMesh"][2]))
        loc_in_mesh_layout.addWidget(self.cmc_loc_x); loc_in_mesh_layout.addWidget(self.cmc_loc_y); loc_in_mesh_layout.addWidget(self.cmc_loc_z)

        self.cmc_allow_free_standing = QCheckBox("allowFreeStandingZoneFaces")
        self.cmc_allow_free_standing.setChecked(cmc["allowFreeStandingZoneFaces"])

        basic_params_layout.addRow("maxLocalCells:", self.cmc_max_local_cells)
        basic_params_layout.addRow("maxGlobalCells:", self.cmc_max_global_cells)
        basic_params_layout.addRow("minRefinementCells:", self.cmc_min_ref_cells)
        basic_params_layout.addRow("maxLoadUnbalance:", self.cmc_max_load_unbalance)
        basic_params_layout.addRow("nCellsBetweenLevels:", self.cmc_n_cells_between_levels)
        basic_params_layout.addRow("locationInMesh (x y z):", loc_in_mesh_layout)
        basic_params_layout.addRow(self.cmc_allow_free_standing)

        tab_layout.addWidget(QLabel("<h3>Castellated Mesh - Basic Parameters</h3>"))
        tab_layout.addWidget(basic_params_group)
        tab_layout.addSpacing(15)

        # Features
        features_group = QWidget()
        features_layout = QVBoxLayout(features_group)
        self.features_table = QTableWidget()
        self.features_table.setColumnCount(3) # File, Level, Action
        self.features_table.setHorizontalHeaderLabels(["Feature File (.eMesh)*", "Refinement Level*", "Action"])
        self.features_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        add_feature_button = QPushButton("Add Feature Edge")
        add_feature_button.clicked.connect(self.add_feature_row)
        features_layout.addWidget(QLabel("<h4>Feature Edge Refinement</h4>"))
        features_layout.addWidget(self.features_table)
        features_layout.addWidget(add_feature_button)
        tab_layout.addWidget(features_group)
        tab_layout.addSpacing(15)

        # Surface Refinement
        surf_ref_group = QWidget()
        surf_ref_layout = QVBoxLayout(surf_ref_group)
        self.surf_ref_table = QTableWidget()
        self.surf_ref_table.setColumnCount(6) # Geometry, MinLvl, MaxLvl, Regions, PatchInfo, Action
        self.surf_ref_table.setHorizontalHeaderLabels(["Geometry Name*", "Min Level*", "Max Level*", "Regions (opt)", "PatchInfo (opt, e.g. {type wall;})", "Action"])
        self.surf_ref_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        add_surf_ref_button = QPushButton("Add Surface Refinement")
        add_surf_ref_button.clicked.connect(self.add_surf_ref_row)
        surf_ref_layout.addWidget(QLabel("<h4>Surface Refinement</h4>"))
        surf_ref_layout.addWidget(self.surf_ref_table)
        surf_ref_layout.addWidget(add_surf_ref_button)
        tab_layout.addWidget(surf_ref_group)
        tab_layout.addSpacing(15)

        # Region Refinement
        region_ref_group = QWidget()
        region_ref_layout = QVBoxLayout(region_ref_group)
        self.region_ref_table = QTableWidget()
        self.region_ref_table.setColumnCount(5) # Geometry, Mode, Levels, (unused), Action
        self.region_ref_table.setHorizontalHeaderLabels(["Geometry Name*", "Mode*", "Levels (dist lvl; dist lvl)*", "Action"])
        self.region_ref_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        add_region_ref_button = QPushButton("Add Region Refinement")
        add_region_ref_button.clicked.connect(self.add_region_ref_row)
        region_ref_layout.addWidget(QLabel("<h4>Region Refinement</h4>"))
        region_ref_layout.addWidget(self.region_ref_table)
        region_ref_layout.addWidget(add_region_ref_button)
        tab_layout.addWidget(region_ref_group)

        self.tabs.addTab(scroll_area, "2. Castellated Mesh")

    def update_castellated_geometry_combos(self):
        geom_names = self.get_defined_geometry_names()
        if not geom_names: geom_names = ["Define Geometry First"]

        for table in [self.surf_ref_table, self.region_ref_table]:
            for r in range(table.rowCount()):
                combo = table.cellWidget(r, 0)
                if isinstance(combo, QComboBox):
                    current_text = combo.currentText()
                    combo.clear()
                    combo.addItems(geom_names)
                    if current_text in geom_names:
                        combo.setCurrentText(current_text)
                    elif geom_names:
                        combo.setCurrentIndex(0)


    def add_feature_row(self, data=None):
        row = self.features_table.rowCount()
        self.features_table.insertRow(row)

        file_edit = QLineEdit(data["file"] if data else "")
        browse_btn = QPushButton("Browse")
        browse_btn.clicked.connect(lambda _, r=row: self.browse_feature_file(r))
        file_widget = QWidget(); file_layout = QHBoxLayout(file_widget); file_layout.setContentsMargins(0,0,0,0)
        file_layout.addWidget(file_edit); file_layout.addWidget(browse_btn)

        level_spin = QSpinBox(value=data["level"] if data else 0)
        level_spin.setRange(0, 10)

        remove_btn = QPushButton("Remove")
        remove_btn.clicked.connect(lambda _, r=row: self.remove_table_row(self.features_table, r))

        self.features_table.setCellWidget(row, 0, file_widget)
        self.features_table.setCellWidget(row, 1, level_spin)
        self.features_table.setCellWidget(row, 2, remove_btn)

    def browse_feature_file(self, row):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Feature File", "", "eMesh Files (*.eMesh);;All Files (*)")
        if file_path:
            file_widget = self.features_table.cellWidget(row, 0)
            if file_widget:
                file_edit = file_widget.findChild(QLineEdit)
                if file_edit: file_edit.setText(file_path)

    def add_surf_ref_row(self, data=None):
        row = self.surf_ref_table.rowCount()
        self.surf_ref_table.insertRow(row)

        geom_combo = QComboBox()
        # geom_names = self.get_defined_geometry_names()
        # geom_combo.addItems(geom_names if geom_names else ["Define Geometry First"])
        # if data and data["geometry"] in geom_names: geom_combo.setCurrentText(data["geometry"])

        min_lvl_spin = QSpinBox(value=data["level_min"] if data else 1); min_lvl_spin.setRange(0,10)
        max_lvl_spin = QSpinBox(value=data["level_max"] if data else 2); max_lvl_spin.setRange(0,10)
        regions_edit = QLineEdit(data["regions"] if data else "")
        patchinfo_edit = QLineEdit(data["patchInfo"] if data else "")
        patchinfo_edit.setPlaceholderText("e.g. { type wall; }")

        remove_btn = QPushButton("Remove")
        remove_btn.clicked.connect(lambda _, r=row: self.remove_table_row(self.surf_ref_table, r))

        self.surf_ref_table.setCellWidget(row, 0, geom_combo) # Populated by on_tab_change
        self.surf_ref_table.setCellWidget(row, 1, min_lvl_spin)
        self.surf_ref_table.setCellWidget(row, 2, max_lvl_spin)
        self.surf_ref_table.setCellWidget(row, 3, regions_edit)
        self.surf_ref_table.setCellWidget(row, 4, patchinfo_edit)
        self.surf_ref_table.setCellWidget(row, 5, remove_btn)
        self.update_castellated_geometry_combos() # Ensure new row combo is populated

    def add_region_ref_row(self, data=None):
        row = self.region_ref_table.rowCount()
        self.region_ref_table.insertRow(row)

        geom_combo = QComboBox()
        # geom_names = self.get_defined_geometry_names()
        # geom_combo.addItems(geom_names if geom_names else ["Define Geometry First"])
        # if data and data["geometry"] in geom_names: geom_combo.setCurrentText(data["geometry"])

        mode_combo = QComboBox(); mode_combo.addItems(["inside", "outside", "distance"])
        if data: mode_combo.setCurrentText(data["mode"])

        levels_edit = QLineEdit(data["levels"] if data else "1.0 1")
        levels_edit.setPlaceholderText("dist1 lvl1; dist2 lvl2; ...")

        remove_btn = QPushButton("Remove")
        remove_btn.clicked.connect(lambda _, r=row: self.remove_table_row(self.region_ref_table, r))

        self.region_ref_table.setCellWidget(row, 0, geom_combo) # Populated by on_tab_change
        self.region_ref_table.setCellWidget(row, 1, mode_combo)
        self.region_ref_table.setCellWidget(row, 2, levels_edit)
        self.region_ref_table.setCellWidget(row, 3, remove_btn)
        self.update_castellated_geometry_combos() # Ensure new row combo is populated

    # --- Tab 3: Snap Controls ---
    def create_snap_controls_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()
        sc = self.snap_controls # Alias

        form_group = QWidget()
        form = QFormLayout(form_group)

        self.sc_n_smooth_patch = QSpinBox(value=sc["nSmoothPatch"]); self.sc_n_smooth_patch.setRange(0,20)
        self.sc_tolerance = QDoubleSpinBox(value=sc["tolerance"]); self.sc_tolerance.setRange(0.1, 10.0); self.sc_tolerance.setSingleStep(0.1)
        self.sc_n_solve_iter = QSpinBox(value=sc["nSolveIter"]); self.sc_n_solve_iter.setRange(0,200)
        self.sc_n_relax_iter = QSpinBox(value=sc["nRelaxIter"]); self.sc_n_relax_iter.setRange(0,50)
        self.sc_n_feature_snap_iter = QSpinBox(value=sc["nFeatureSnapIter"]); self.sc_n_feature_snap_iter.setRange(0,50)

        self.sc_implicit_snap = QCheckBox("implicitFeatureSnap"); self.sc_implicit_snap.setChecked(sc["implicitFeatureSnap"])
        self.sc_explicit_snap = QCheckBox("explicitFeatureSnap"); self.sc_explicit_snap.setChecked(sc["explicitFeatureSnap"])
        self.sc_multi_region_snap = QCheckBox("multiRegionFeatureSnap"); self.sc_multi_region_snap.setChecked(sc["multiRegionFeatureSnap"])

        form.addRow("nSmoothPatch:", self.sc_n_smooth_patch)
        form.addRow("tolerance (relative to cell size):", self.sc_tolerance)
        form.addRow("nSolveIter (mesh displacement):", self.sc_n_solve_iter)
        form.addRow("nRelaxIter (snapping):", self.sc_n_relax_iter)
        form.addRow("nFeatureSnapIter:", self.sc_n_feature_snap_iter)
        form.addRow(self.sc_implicit_snap)
        form.addRow(self.sc_explicit_snap)
        form.addRow(self.sc_multi_region_snap)

        tab_layout.addWidget(QLabel("<h3>Snapping Controls</h3>"))
        tab_layout.addWidget(form_group)
        self.tabs.addTab(scroll_area, "3. Snap Controls")

    # --- Tab 4: Add Layers ---
    def create_add_layers_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()
        alc = self.add_layers_controls # Alias

        # General Layer Parameters
        general_layers_group = QWidget()
        general_layers_form = QFormLayout(general_layers_group)

        self.alc_relative_sizes = QCheckBox("relativeSizes"); self.alc_relative_sizes.setChecked(alc["relativeSizes"])
        self.alc_expansion_ratio = QDoubleSpinBox(value=alc["expansionRatio"]); self.alc_expansion_ratio.setRange(1.0, 3.0); self.alc_expansion_ratio.setSingleStep(0.05)
        self.alc_final_layer_thickness = QDoubleSpinBox(value=alc["finalLayerThickness"]); self.alc_final_layer_thickness.setRange(0.01, 5.0); self.alc_final_layer_thickness.setSingleStep(0.01)
        self.alc_min_thickness = QDoubleSpinBox(value=alc["minThickness"]); self.alc_min_thickness.setRange(0.001, 2.0); self.alc_min_thickness.setSingleStep(0.001)
        self.alc_n_grow = QSpinBox(value=alc["nGrow"]); self.alc_n_grow.setRange(0,10)
        self.alc_feature_angle = QDoubleSpinBox(value=alc["featureAngle"]); self.alc_feature_angle.setRange(0,180)
        self.alc_max_face_thickness_ratio = QDoubleSpinBox(value=alc["maxFaceThicknessRatio"]); self.alc_max_face_thickness_ratio.setRange(0.1,1.0); self.alc_max_face_thickness_ratio.setSingleStep(0.05)
        self.alc_n_smooth_surf_norm = QSpinBox(value=alc["nSmoothSurfaceNormals"]); self.alc_n_smooth_surf_norm.setRange(0,10)
        self.alc_n_smooth_thickness = QSpinBox(value=alc["nSmoothThickness"]); self.alc_n_smooth_thickness.setRange(0,20)
        self.alc_slip_feature_angle = QDoubleSpinBox(value=alc["slipFeatureAngle"]); self.alc_slip_feature_angle.setRange(0,90)
        self.alc_n_buffer_cells = QSpinBox(value=alc["nBufferCellsNoExtrude"]); self.alc_n_buffer_cells.setRange(0,10)
        self.alc_n_layer_iter = QSpinBox(value=alc["nLayerIter"]); self.alc_n_layer_iter.setRange(0,100)

        general_layers_form.addRow(self.alc_relative_sizes)
        general_layers_form.addRow("expansionRatio:", self.alc_expansion_ratio)
        general_layers_form.addRow("finalLayerThickness:", self.alc_final_layer_thickness)
        general_layers_form.addRow("minThickness:", self.alc_min_thickness)
        general_layers_form.addRow("nGrow (overall default):", self.alc_n_grow)
        general_layers_form.addRow("featureAngle (stop layers):", self.alc_feature_angle)
        general_layers_form.addRow("maxFaceThicknessRatio:", self.alc_max_face_thickness_ratio)
        general_layers_form.addRow("nSmoothSurfaceNormals:", self.alc_n_smooth_surf_norm)
        general_layers_form.addRow("nSmoothThickness:", self.alc_n_smooth_thickness)
        general_layers_form.addRow("slipFeatureAngle:", self.alc_slip_feature_angle)
        general_layers_form.addRow("nBufferCellsNoExtrude:", self.alc_n_buffer_cells)
        general_layers_form.addRow("nLayerIter (max iterations):", self.alc_n_layer_iter)

        tab_layout.addWidget(QLabel("<h3>Add Layers - General Parameters</h3>"))
        tab_layout.addWidget(general_layers_group)
        tab_layout.addSpacing(15)

        # Per-Patch Layers
        patch_layers_group = QWidget()
        patch_layers_layout = QVBoxLayout(patch_layers_group)
        self.patch_layers_table = QTableWidget()
        self.patch_layers_table.setColumnCount(3) # PatchName, nSurfaceLayers, Action
        self.patch_layers_table.setHorizontalHeaderLabels(["Patch Name*", "nSurfaceLayers*", "Action"])
        self.patch_layers_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        add_patch_layer_button = QPushButton("Add Patch Layer Setting")
        add_patch_layer_button.clicked.connect(self.add_patch_layer_row)

        patch_layers_layout.addWidget(QLabel("<h4>Per-Patch Layer Settings</h4>"))
        patch_layers_layout.addWidget(QLabel("<small><i>Patch names should match geometry names or defined regions.</i></small>"))
        patch_layers_layout.addWidget(self.patch_layers_table)
        patch_layers_layout.addWidget(add_patch_layer_button)
        tab_layout.addWidget(patch_layers_group)

        self.tabs.addTab(scroll_area, "4. Add Layers")

    def update_add_layers_patch_combos(self):
        patch_names = self.get_potential_patch_names()
        if not patch_names: patch_names = ["Define Geometry First"]

        for r in range(self.patch_layers_table.rowCount()):
            combo = self.patch_layers_table.cellWidget(r, 0)
            if isinstance(combo, QComboBox):
                current_text = combo.currentText()
                combo.clear()
                combo.addItems(patch_names)
                if current_text in patch_names:
                    combo.setCurrentText(current_text)
                elif patch_names:
                    combo.setCurrentIndex(0)

    def add_patch_layer_row(self, data=None):
        row = self.patch_layers_table.rowCount()
        self.patch_layers_table.insertRow(row)

        patch_combo = QComboBox() # Populated by on_tab_change
        # patch_names = self.get_potential_patch_names()
        # patch_combo.addItems(patch_names if patch_names else ["Define Geometry First"])
        # if data and data["patchName"] in patch_names: patch_combo.setCurrentText(data["patchName"])

        n_layers_spin = QSpinBox(value=data["nSurfaceLayers"] if data else 3)
        n_layers_spin.setRange(0, 20)

        remove_btn = QPushButton("Remove")
        remove_btn.clicked.connect(lambda _, r=row: self.remove_table_row(self.patch_layers_table, r))

        self.patch_layers_table.setCellWidget(row, 0, patch_combo)
        self.patch_layers_table.setCellWidget(row, 1, n_layers_spin)
        self.patch_layers_table.setCellWidget(row, 2, remove_btn)
        self.update_add_layers_patch_combos() # Ensure new row combo is populated


    # --- Tab 5: Mesh Quality ---
    def create_mesh_quality_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()
        mqc = self.mesh_quality_controls # Alias

        form_group = QWidget()
        form = QFormLayout(form_group)

        self.mqc_max_non_ortho = QDoubleSpinBox(value=mqc["maxNonOrtho"]); self.mqc_max_non_ortho.setRange(0,90)
        self.mqc_max_boundary_skew = QDoubleSpinBox(value=mqc["maxBoundarySkewness"]); self.mqc_max_boundary_skew.setRange(0,90)
        self.mqc_max_internal_skew = QDoubleSpinBox(value=mqc["maxInternalSkewness"]); self.mqc_max_internal_skew.setRange(0,10)
        self.mqc_max_concave = QDoubleSpinBox(value=mqc["maxConcave"]); self.mqc_max_concave.setRange(0,180)
        # minFlatness is not standard, let's use minFaceWeight or minDeterminant as examples
        self.mqc_min_vol = QLineEdit(str(mqc["minVol"])) # Scientific notation possible
        self.mqc_min_tet_quality = QLineEdit(str(mqc["minTetQuality"]))
        self.mqc_min_area = QLineEdit(str(mqc["minArea"]))
        self.mqc_min_twist = QDoubleSpinBox(value=mqc["minTwist"]); self.mqc_min_twist.setRange(0,1); self.mqc_min_twist.setSingleStep(0.01)
        self.mqc_min_determinant = QDoubleSpinBox(value=mqc["minDeterminant"]); self.mqc_min_determinant.setRange(0,1); self.mqc_min_determinant.setSingleStep(0.001)
        self.mqc_min_face_weight = QDoubleSpinBox(value=mqc["minFaceWeight"]); self.mqc_min_face_weight.setRange(0,0.5); self.mqc_min_face_weight.setSingleStep(0.01)
        self.mqc_min_vol_ratio = QDoubleSpinBox(value=mqc["minVolRatio"]); self.mqc_min_vol_ratio.setRange(0,1); self.mqc_min_vol_ratio.setSingleStep(0.01)
        self.mqc_min_triangle_twist = QLineEdit(str(mqc["minTriangleTwist"]))

        self.mqc_n_smooth_scale = QSpinBox(value=mqc["nSmoothScale"]); self.mqc_n_smooth_scale.setRange(0,10)
        self.mqc_error_reduction = QDoubleSpinBox(value=mqc["errorReduction"]); self.mqc_error_reduction.setRange(0.1,1.0); self.mqc_error_reduction.setSingleStep(0.05)

        form.addRow("maxNonOrtho:", self.mqc_max_non_ortho)
        form.addRow("maxBoundarySkewness:", self.mqc_max_boundary_skew)
        form.addRow("maxInternalSkewness:", self.mqc_max_internal_skew)
        form.addRow("maxConcave:", self.mqc_max_concave)
        form.addRow("minVol (absolute):", self.mqc_min_vol)
        form.addRow("minTetQuality:", self.mqc_min_tet_quality)
        form.addRow("minArea (absolute, -1 to disable):", self.mqc_min_area)
        form.addRow("minTwist:", self.mqc_min_twist)
        form.addRow("minDeterminant (1 for hex):", self.mqc_min_determinant)
        form.addRow("minFaceWeight (0-0.5):", self.mqc_min_face_weight)
        form.addRow("minVolRatio (cell-to-cell):", self.mqc_min_vol_ratio)
        form.addRow("minTriangleTwist (-1 to disable):", self.mqc_min_triangle_twist)
        form.addRow("nSmoothScale (smoothing iterations):", self.mqc_n_smooth_scale)
        form.addRow("errorReduction (smoother):", self.mqc_error_reduction)

        tab_layout.addWidget(QLabel("<h3>Mesh Quality Controls</h3>"))
        tab_layout.addWidget(form_group)
        tab_layout.addSpacing(15)

        # Relaxed Controls (Optional)
        relaxed_group = QWidget()
        relaxed_layout = QFormLayout(relaxed_group)
        self.mqc_relaxed_enabled = QCheckBox("Enable Relaxed Controls")
        self.mqc_relaxed_enabled.setChecked(mqc["relaxed"]["enabled"])
        self.mqc_relaxed_max_non_ortho = QDoubleSpinBox(value=mqc["relaxed"]["maxNonOrtho"])
        self.mqc_relaxed_max_non_ortho.setRange(0,90)
        self.mqc_relaxed_enabled.toggled.connect(self.mqc_relaxed_max_non_ortho.setEnabled)
        self.mqc_relaxed_max_non_ortho.setEnabled(mqc["relaxed"]["enabled"])

        relaxed_layout.addRow(self.mqc_relaxed_enabled)
        relaxed_layout.addRow("Relaxed maxNonOrtho:", self.mqc_relaxed_max_non_ortho)
        tab_layout.addWidget(QLabel("<h4>Relaxed Quality Controls (Optional)</h4>"))
        tab_layout.addWidget(relaxed_group)

        self.tabs.addTab(scroll_area, "5. Mesh Quality")

    # --- Tab 6: Advanced & Output ---
    def create_advanced_output_tab(self):
        scroll_area, tab_layout = self.create_scrollable_tab()

        form_group = QWidget()
        form = QFormLayout(form_group)

        self.adv_merge_tolerance = QLineEdit(str(self.general_settings["mergeTolerance"]))
        self.adv_merge_tolerance.setPlaceholderText("e.g., 1e-6")

        self.adv_debug_flags = QLineEdit(", ".join(self.debug_flags))
        self.adv_debug_flags.setPlaceholderText("mesh, snapping, refinement, layers (comma-sep)")

        self.adv_write_flags = QLineEdit(", ".join(self.write_flags))
        self.adv_write_flags.setPlaceholderText("scalarLevels, layerSets, refinementHistory (comma-sep)")

        form.addRow("mergeTolerance:", self.adv_merge_tolerance)
        form.addRow("Debug Flags:", self.adv_debug_flags)
        form.addRow("Write Flags:", self.adv_write_flags)

        tab_layout.addWidget(QLabel("<h3>Advanced & Output Flags</h3>"))
        tab_layout.addWidget(form_group)
        self.tabs.addTab(scroll_area, "6. Advanced")


    # --- Tab 7: Generate ---
    def create_generate_tab(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)

        self.shm_dict_preview = QTextEdit()
        self.shm_dict_preview.setReadOnly(True)
        self.shm_dict_preview.setFontFamily("monospace")
        self.shm_dict_preview.setLineWrapMode(QTextEdit.LineWrapMode.NoWrap)


        generate_button = QPushButton("Generate snappyHexMeshDict")
        generate_button.clicked.connect(self.collect_data_and_generate)

        save_button = QPushButton("Save snappyHexMeshDict to File...")
        save_button.clicked.connect(self.save_shm_dict_to_file)

        layout.addWidget(QLabel("<h3>snappyHexMeshDict Preview</h3>"))
        layout.addWidget(self.shm_dict_preview)

        button_layout = QHBoxLayout()
        button_layout.addWidget(generate_button)
        button_layout.addWidget(save_button)
        layout.addLayout(button_layout)

        self.tabs.addTab(tab, "7. Generate")

    def collect_data_and_generate(self):
        """Collect data from all UI elements before calling generate."""
        try:
            # Tab 1: General & Geometry
            self.general_settings["castellatedMesh"] = self.cb_castellated.isChecked()
            self.general_settings["snap"] = self.cb_snap.isChecked()
            self.general_settings["addLayers"] = self.cb_add_layers.isChecked()
            self.general_settings["convertToMeters"] = float(self.le_convert_to_meters.text())

            self.geometries = []
            for r in range(self.geometry_table.rowCount()):
                name = self.geometry_table.cellWidget(r,0).text()
                gtype = self.geometry_table.cellWidget(r,1).currentText()
                file_widget = self.geometry_table.cellWidget(r,2)
                gfile = file_widget.findChild(QLineEdit).text() if file_widget else ""
                regions = self.geometry_table.cellWidget(r,3).text()
                if name and gtype and gfile: # Only add if essential fields are present
                     self.geometries.append({"name": name, "type": gtype, "file": gfile, "regions": regions})

            # Tab 2: Castellated Mesh
            cmc = self.castellated_mesh_controls
            cmc["maxLocalCells"] = self.cmc_max_local_cells.value()
            cmc["maxGlobalCells"] = self.cmc_max_global_cells.value()
            cmc["minRefinementCells"] = self.cmc_min_ref_cells.value()
            cmc["maxLoadUnbalance"] = self.cmc_max_load_unbalance.value()
            cmc["nCellsBetweenLevels"] = self.cmc_n_cells_between_levels.value()
            cmc["locationInMesh"] = [float(self.cmc_loc_x.text()), float(self.cmc_loc_y.text()), float(self.cmc_loc_z.text())]
            cmc["allowFreeStandingZoneFaces"] = self.cmc_allow_free_standing.isChecked()

            cmc["features"] = []
            for r in range(self.features_table.rowCount()):
                file_widget = self.features_table.cellWidget(r,0)
                ffile = file_widget.findChild(QLineEdit).text() if file_widget else ""
                flevel = self.features_table.cellWidget(r,1).value()
                if ffile: cmc["features"].append({"file": ffile, "level": flevel})

            cmc["refinementSurfaces"] = []
            for r in range(self.surf_ref_table.rowCount()):
                s_geom = self.surf_ref_table.cellWidget(r,0).currentText()
                s_minl = self.surf_ref_table.cellWidget(r,1).value()
                s_maxl = self.surf_ref_table.cellWidget(r,2).value()
                s_regions = self.surf_ref_table.cellWidget(r,3).text()
                s_patchinfo = self.surf_ref_table.cellWidget(r,4).text()
                if s_geom and s_geom != "Define Geometry First":
                    cmc["refinementSurfaces"].append({
                        "geometry": s_geom, "level_min": s_minl, "level_max": s_maxl,
                        "regions": s_regions, "patchInfo": s_patchinfo
                    })

            cmc["refinementRegions"] = []
            for r in range(self.region_ref_table.rowCount()):
                rr_geom = self.region_ref_table.cellWidget(r,0).currentText()
                rr_mode = self.region_ref_table.cellWidget(r,1).currentText()
                rr_levels = self.region_ref_table.cellWidget(r,2).text()
                if rr_geom and rr_geom != "Define Geometry First" and rr_levels:
                     cmc["refinementRegions"].append({"geometry": rr_geom, "mode": rr_mode, "levels": rr_levels})


            # Tab 3: Snap Controls
            sc = self.snap_controls
            sc["nSmoothPatch"] = self.sc_n_smooth_patch.value()
            sc["tolerance"] = self.sc_tolerance.value()
            sc["nSolveIter"] = self.sc_n_solve_iter.value()
            sc["nRelaxIter"] = self.sc_n_relax_iter.value()
            sc["nFeatureSnapIter"] = self.sc_n_feature_snap_iter.value()
            sc["implicitFeatureSnap"] = self.sc_implicit_snap.isChecked()
            sc["explicitFeatureSnap"] = self.sc_explicit_snap.isChecked()
            sc["multiRegionFeatureSnap"] = self.sc_multi_region_snap.isChecked()

            # Tab 4: Add Layers
            alc = self.add_layers_controls
            alc["relativeSizes"] = self.alc_relative_sizes.isChecked()
            alc["expansionRatio"] = self.alc_expansion_ratio.value()
            alc["finalLayerThickness"] = self.alc_final_layer_thickness.value()
            alc["minThickness"] = self.alc_min_thickness.value()
            alc["nGrow"] = self.alc_n_grow.value()
            alc["featureAngle"] = self.alc_feature_angle.value()
            alc["maxFaceThicknessRatio"] = self.alc_max_face_thickness_ratio.value()
            alc["nSmoothSurfaceNormals"] = self.alc_n_smooth_surf_norm.value()
            alc["nSmoothThickness"] = self.alc_n_smooth_thickness.value()
            alc["slipFeatureAngle"] = self.alc_slip_feature_angle.value()
            alc["nBufferCellsNoExtrude"] = self.alc_n_buffer_cells.value()
            alc["nLayerIter"] = self.alc_n_layer_iter.value()
            alc["layers"] = []
            for r in range(self.patch_layers_table.rowCount()):
                patch_name = self.patch_layers_table.cellWidget(r,0).currentText()
                n_surf_layers = self.patch_layers_table.cellWidget(r,1).value()
                if patch_name and patch_name != "Define Geometry First":
                    alc["layers"].append({"patchName": patch_name, "nSurfaceLayers": n_surf_layers})

            # Tab 5: Mesh Quality
            mqc = self.mesh_quality_controls
            mqc["maxNonOrtho"] = self.mqc_max_non_ortho.value()
            mqc["maxBoundarySkewness"] = self.mqc_max_boundary_skew.value()
            mqc["maxInternalSkewness"] = self.mqc_max_internal_skew.value()
            mqc["maxConcave"] = self.mqc_max_concave.value()
            mqc["minVol"] = float(self.mqc_min_vol.text())
            mqc["minTetQuality"] = float(self.mqc_min_tet_quality.text())
            mqc["minArea"] = float(self.mqc_min_area.text())
            mqc["minTwist"] = self.mqc_min_twist.value()
            mqc["minDeterminant"] = self.mqc_min_determinant.value()
            mqc["minFaceWeight"] = self.mqc_min_face_weight.value()
            mqc["minVolRatio"] = self.mqc_min_vol_ratio.value()
            mqc["minTriangleTwist"] = float(self.mqc_min_triangle_twist.text())
            mqc["nSmoothScale"] = self.mqc_n_smooth_scale.value()
            mqc["errorReduction"] = self.mqc_error_reduction.value()
            mqc["relaxed"]["enabled"] = self.mqc_relaxed_enabled.isChecked()
            mqc["relaxed"]["maxNonOrtho"] = self.mqc_relaxed_max_non_ortho.value()

            # Tab 6: Advanced
            self.general_settings["mergeTolerance"] = float(self.adv_merge_tolerance.text())
            self.debug_flags = [f.strip() for f in self.adv_debug_flags.text().split(',') if f.strip()]
            self.write_flags = [f.strip() for f in self.adv_write_flags.text().split(',') if f.strip()]


        except ValueError as e:
            QMessageBox.critical(self, "Input Error", f"Invalid numeric input: {e}")
            return
        except Exception as e:
            QMessageBox.critical(self, "Error Collecting Data", f"An unexpected error occurred: {e}")
            return

        self.generate_shm_dict_content()
        self.statusBar().showMessage("snappyHexMeshDict generated/updated.")
        self.tabs.setCurrentIndex(self.tabs.count()-1) # Switch to generate tab

    def generate_shm_dict_content(self):
        """Generates the string content for snappyHexMeshDict."""
        # Helper for boolean to string
        def b(val): return "true" if val else "false"
        def format_list_of_strings(lst):
            if not lst: return ""
            return "\n    ".join(f'"{s}"' for s in lst)


        content = []
        content.append("/*--------------------------------*- C++ -*----------------------------------*\\")
        content.append("| =========                 |                                                 |")
        content.append("| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |")
        content.append("|  \\\\    /   O peration     | Version:  v2312 (example)                       |")
        content.append("|   \\\\  /    A nd           | Website:  www.OpenFOAM.com                      |")
        content.append("|    \\\\/     M anipulation  | Generated by PyQt SnappyHexMesh GUI             |")
        content.append("\\*---------------------------------------------------------------------------*/")
        content.append("FoamFile")
        content.append("{")
        content.append("    version     2.0;")
        content.append("    format      ascii;")
        content.append("    class       dictionary;")
        content.append("    object      snappyHexMeshDict;")
        content.append("}")
        content.append("// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //")
        content.append("")

        gs = self.general_settings
        content.append(f"castellatedMesh {b(gs['castellatedMesh'])};")
        content.append(f"snap            {b(gs['snap'])};")
        content.append(f"addLayers       {b(gs['addLayers'])};")
        content.append("")
        content.append(f"convertToMeters {gs['convertToMeters']};")
        content.append("")

        # Geometry
        content.append("geometry")
        content.append("{")
        for geo in self.geometries:
            content.append(f"    {geo['name']}")
            content.append("    {")
            content.append(f"        type {geo['type']};")
            content.append(f"        file \"{geo['file']}\";")
            if geo['regions']: # Handle named regions within STL
                content.append("        regions")
                content.append("        {")
                regions_list = [r.strip() for r in geo['regions'].split(',') if r.strip()]
                for region_item in regions_list:
                    # Assuming region_item could be "regionName { name aliasName; }" or just "regionName"
                    # For simplicity, if it contains '{', assume it's a full entry
                    if '{' in region_item and '}' in region_item:
                        content.append(f"            {region_item}") # User provides full sub-dict
                    else: # Assume it's just a name, create a simple entry
                        content.append(f"            {region_item} {{ name {region_item}; }}")
                content.append("        }")
            content.append("    }")
        content.append("};")
        content.append("")

        # CastellatedMeshControls
        cmc = self.castellated_mesh_controls
        content.append("castellatedMeshControls")
        content.append("{")
        content.append(f"    maxLocalCells               {cmc['maxLocalCells']};")
        content.append(f"    maxGlobalCells              {cmc['maxGlobalCells']};")
        content.append(f"    minRefinementCells          {cmc['minRefinementCells']};")
        content.append(f"    maxLoadUnbalance            {cmc['maxLoadUnbalance']:.2f};")
        content.append(f"    nCellsBetweenLevels         {cmc['nCellsBetweenLevels']};")
        content.append("")
        content.append(f"    locationInMesh              ({cmc['locationInMesh'][0]} {cmc['locationInMesh'][1]} {cmc['locationInMesh'][2]});")
        content.append(f"    allowFreeStandingZoneFaces  {b(cmc['allowFreeStandingZoneFaces'])};")
        content.append("")

        content.append("    features")
        content.append("    (")
        for f in cmc["features"]:
            content.append(f"        {{ file \"{f['file']}\"; level {f['level']}; }}")
        content.append("    );")
        content.append("")

        content.append("    refinementSurfaces")
        content.append("    {")
        for rs in cmc["refinementSurfaces"]:
            content.append(f"        {rs['geometry']}") # Geometry name is the key
            content.append("        {")
            content.append(f"            level ({rs['level_min']} {rs['level_max']});")
            if rs['regions']:
                content.append("            regions")
                content.append("            {")
                # Assuming regions are comma-separated simple names for now
                # e.g. "region1 { level (2 3); patchInfo { type wall; } }, region2 { level (3 3); }"
                # For the GUI, we'll keep it simpler: user types the full content for the regions sub-dict
                # This is a complex part; for now, we'll assume user puts the region details in the string.
                # A more robust GUI would have a sub-table for regions within refinementSurfaces.
                # Example: "wing { level (2 3); }"
                # If rs['regions'] is "wing { level (2 3); }", it will be printed as is.
                # For multiple, they'd be comma separated in the input field.
                # This is a simplification.
                content.append(f"                {rs['regions']} // User provided region refinement details")
                content.append("            }")
            if rs['patchInfo']: # User types the content of patchInfo, e.g. "{ type wall; }"
                content.append(f"            patchInfo {rs['patchInfo']};")
            content.append("        }")
        content.append("    }")
        content.append("")

        content.append("    refinementRegions")
        content.append("    {")
        for rr in cmc["refinementRegions"]:
            content.append(f"        {rr['geometry']}") # Geometry name is the key
            content.append("        {")
            content.append(f"            mode {rr['mode']};")
            content.append("            levels (")
            # Parse "dist1 lvl1; dist2 lvl2" into OpenFOAM list of lists
            levels_str_list = []
            for pair_str in rr['levels'].split(';'):
                pair = pair_str.strip().split()
                if len(pair) == 2:
                    levels_str_list.append(f"({pair[0]} {pair[1]})")
            content.append(f"                {' '.join(levels_str_list)}")
            content.append("            );")
            content.append("        }")
        content.append("    }")
        content.append("}")
        content.append("")

        # SnapControls
        sc = self.snap_controls
        content.append("snapControls")
        content.append("{")
        content.append(f"    nSmoothPatch            {sc['nSmoothPatch']};")
        content.append(f"    tolerance               {sc['tolerance']:.1f};")
        content.append(f"    nSolveIter              {sc['nSolveIter']};")
        content.append(f"    nRelaxIter              {sc['nRelaxIter']};")
        content.append(f"    nFeatureSnapIter        {sc['nFeatureSnapIter']}; // Optional: if > nRelaxIter, uses this for features")
        content.append(f"    implicitFeatureSnap     {b(sc['implicitFeatureSnap'])};")
        content.append(f"    explicitFeatureSnap     {b(sc['explicitFeatureSnap'])};")
        content.append(f"    multiRegionFeatureSnap  {b(sc['multiRegionFeatureSnap'])};")
        content.append("}")
        content.append("")

        # AddLayersControls
        alc = self.add_layers_controls
        content.append("addLayersControls")
        content.append("{")
        content.append(f"    relativeSizes           {b(alc['relativeSizes'])};")
        content.append(f"    expansionRatio          {alc['expansionRatio']:.2f};")
        content.append(f"    finalLayerThickness     {alc['finalLayerThickness']:.3f};")
        content.append(f"    minThickness            {alc['minThickness']:.3f};")
        content.append(f"    nGrow                   {alc['nGrow']};")
        content.append(f"    featureAngle            {alc['featureAngle']:.1f};")
        content.append(f"    maxFaceThicknessRatio   {alc['maxFaceThicknessRatio']:.2f};")
        content.append(f"    nSmoothSurfaceNormals   {alc['nSmoothSurfaceNormals']};")
        content.append(f"    nSmoothThickness        {alc['nSmoothThickness']};")
        content.append(f"    slipFeatureAngle        {alc['slipFeatureAngle']:.1f};")
        content.append(f"    nBufferCellsNoExtrude   {alc['nBufferCellsNoExtrude']};")
        content.append(f"    nLayerIter              {alc['nLayerIter']};")
        content.append("")
        content.append("    layers")
        content.append("    {")
        for layer_patch in alc["layers"]:
            content.append(f"        \"{layer_patch['patchName']}\" // Ensure this patchName is correct (from geometry or region)")
            content.append("        {")
            content.append(f"            nSurfaceLayers {layer_patch['nSurfaceLayers']};")
            content.append("        }")
        content.append("    }")
        content.append("}")
        content.append("")

        # MeshQualityControls
        mqc = self.mesh_quality_controls
        content.append("meshQualityControls")
        content.append("{")
        content.append(f"    maxNonOrtho             {mqc['maxNonOrtho']:.1f};")
        content.append(f"    maxBoundarySkewness     {mqc['maxBoundarySkewness']:.1f};")
        content.append(f"    maxInternalSkewness     {mqc['maxInternalSkewness']:.1f};")
        content.append(f"    maxConcave              {mqc['maxConcave']:.1f};")
        content.append(f"    minVol                  {mqc['minVol']:.2e};")
        content.append(f"    minTetQuality           {mqc['minTetQuality']:.2e};")
        content.append(f"    minArea                 {mqc['minArea']:.1f};")
        content.append(f"    minTwist                {mqc['minTwist']:.3f};")
        content.append(f"    minDeterminant          {mqc['minDeterminant']:.4f};")
        content.append(f"    minFaceWeight           {mqc['minFaceWeight']:.3f};")
        content.append(f"    minVolRatio             {mqc['minVolRatio']:.3f};")
        content.append(f"    minTriangleTwist        {mqc['minTriangleTwist']:.1f};")
        content.append("")
        content.append(f"    nSmoothScale            {mqc['nSmoothScale']};")
        content.append(f"    errorReduction          {mqc['errorReduction']:.2f};")
        if mqc["relaxed"]["enabled"]:
            content.append("    relaxed")
            content.append("    {")
            content.append(f"        maxNonOrtho         {mqc['relaxed']['maxNonOrtho']:.1f};")
            content.append("    }")
        content.append("}")
        content.append("")

        # Advanced
        content.append(f"mergeTolerance {gs['mergeTolerance']:.1e};")
        content.append("")

        if self.debug_flags:
            content.append("debugFlags")
            content.append("(")
            content.append(f"    {format_list_of_strings(self.debug_flags)}")
            content.append(");")
            content.append("")

        if self.write_flags:
            content.append("writeFlags")
            content.append("(")
            content.append(f"    {format_list_of_strings(self.write_flags)}")
            content.append(");")
            content.append("")

        content.append("// ************************************************************************* //")
        self.shm_dict_preview.setText("\n".join(content))


    def save_shm_dict_to_file(self):
        content = self.shm_dict_preview.toPlainText()
        if not content:
            QMessageBox.warning(self, "Save Error", "No snappyHexMeshDict content to save. Please generate it first.")
            return

        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Save snappyHexMeshDict",
            "snappyHexMeshDict",
            "All Files (*);;OpenFOAM Dictionary Files (snappyHexMeshDict*)"
        )

        if file_path:
            try:
                with open(file_path, 'w') as f:
                    f.write(content)
                self.statusBar().showMessage(f"snappyHexMeshDict saved to {file_path}")
            except Exception as e:
                QMessageBox.critical(self, "Save Error", f"Could not save file: {e}")
                self.statusBar().showMessage(f"Error saving file: {e}")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # Apply a simple stylesheet for a slightly more "technical" look
    app.setStyleSheet("""
        QWidget {
            font-size: 9pt; /* Slightly smaller default font for more content */
        }
        QMainWindow {
            background-color: #f0f0f0;
        }
        QTabWidget::pane {
            border: 1px solid #c0c0c0;
            background-color: white;
        }
        QTabBar::tab {
            background: #e1e1e1;
            border: 1px solid #c0c0c0;
            border-bottom-color: #c0c0c0;
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
            min-width: 15ex; /* Wider tabs */
            padding: 6px 12px;
            margin-right: 2px;
        }
        QTabBar::tab:selected {
            background: white;
            margin-bottom: -1px;
        }
        QTabBar::tab:!selected:hover {
            background: #d5d5d5;
        }
        QPushButton {
            padding: 5px 10px;
            background-color: #e0e0e0;
            border: 1px solid #b0b0b0;
            border-radius: 3px;
            min-width: 80px;
        }
        QPushButton:hover {
            background-color: #d0d0d0;
        }
        QPushButton:pressed {
            background-color: #c0c0c0;
        }
        QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox {
            padding: 4px;
            border: 1px solid #c0c0c0;
            border-radius: 3px;
            min-height: 18px; /* Ensure consistent height */
        }
        QTableWidget {
            gridline-color: #d0d0d0;
            background-color: #ffffff;
        }
        QHeaderView::section {
            background-color: #f0f0f0;
            padding: 4px;
            border: 1px solid #d0d0d0;
            font-weight: bold;
        }
        QTextEdit {
             border: 1px solid #c0c0c0;
             background-color: #fdfdfd;
        }
        QLabel {
            padding-top: 3px;
            padding-bottom: 3px;
        }
        QLabel[accessibleName="groupLabel"] { /* For custom styling of group labels if needed */
            font-weight: bold;
            font-size: 10pt;
            margin-top: 5px;
            margin-bottom: 2px;
        }
        QScrollArea {
            border: none;
        }
        QWidget { /* Content widget inside scroll area */
            background-color: white;
        }
    """)

    main_window = SnappyHexMeshApp()
    main_window.show()
    sys.exit(app.exec())