# -*- coding: utf-8 -*-
"""PyQt6 blockMeshDict Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1romFkVdAUw_Znx1su00Dp2P0AkM9hdRv
"""

import sys
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QTabWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QFormLayout, QLineEdit, QPushButton, QTableWidget, QTableWidgetItem,
    QComboBox, QMessageBox, QTextEdit, QFileDialog, QLabel, QHeaderView,
    QSpinBox
)
from PyQt5.QtCore import Qt, QRegularExpression
from PyQt5.QtGui import QRegularExpressionValidator

class BlockMeshApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("PyQt blockMeshDict Generator (ICEM Style)")
        self.setGeometry(100, 100, 1200, 800)

        # Data storage
        self.vertices = []  # List of [id, x, y, z]
        self.blocks = []    # List of [id, [v_ids], (nx,ny,nz), (gx,gy,gz)]
        self.patches = []   # List of [name, type, block_id, face_label, [face_v_ids]]

        self.vertex_id_counter = 0
        self.block_id_counter = 0

        self.init_ui()

    def init_ui(self):
        self.tabs = QTabWidget()
        self.setCentralWidget(self.tabs)

        # Create tabs
        self.create_vertices_tab()
        self.create_blocks_tab()
        self.create_patches_tab()
        self.create_generate_tab()

        # Status bar (optional, for messages)
        self.statusBar().showMessage("Ready")

    def create_vertices_tab(self):
        tab = QWidget()
        layout = QHBoxLayout(tab)

        # Left side: Input form
        form_layout_widget = QWidget()
        form_layout = QFormLayout(form_layout_widget)
        form_layout_widget.setMaximumWidth(300)

        self.vertex_x_input = QLineEdit()
        self.vertex_y_input = QLineEdit()
        self.vertex_z_input = QLineEdit()

        # Validator for float numbers
        float_validator = QRegularExpressionValidator(QRegularExpression(r"^-?\d*\.?\d+$"))
        self.vertex_x_input.setValidator(float_validator)
        self.vertex_y_input.setValidator(float_validator)
        self.vertex_z_input.setValidator(float_validator)

        form_layout.addRow("X:", self.vertex_x_input)
        form_layout.addRow("Y:", self.vertex_y_input)
        form_layout.addRow("Z:", self.vertex_z_input)

        add_vertex_button = QPushButton("Add Vertex")
        add_vertex_button.clicked.connect(self.add_vertex)
        form_layout.addRow(add_vertex_button)

        self.edit_vertex_id_input = QSpinBox()
        self.edit_vertex_id_input.setMinimum(-1) # -1 for no selection
        self.edit_vertex_id_input.setValue(-1)
        form_layout.addRow("Edit Vertex ID:", self.edit_vertex_id_input)

        load_vertex_button = QPushButton("Load Vertex for Editing")
        load_vertex_button.clicked.connect(self.load_vertex_for_editing)
        form_layout.addRow(load_vertex_button)

        update_vertex_button = QPushButton("Update Vertex")
        update_vertex_button.clicked.connect(self.update_vertex)
        form_layout.addRow(update_vertex_button)


        layout.addWidget(form_layout_widget)

        # Right side: Table of vertices
        table_widget = QWidget()
        table_layout = QVBoxLayout(table_widget)

        self.vertices_table = QTableWidget()
        self.vertices_table.setColumnCount(4)
        self.vertices_table.setHorizontalHeaderLabels(["ID", "X", "Y", "Z"])
        self.vertices_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.vertices_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers) # Read-only
        self.vertices_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)


        delete_vertex_button = QPushButton("Delete Selected Vertex")
        delete_vertex_button.clicked.connect(self.delete_vertex)

        table_layout.addWidget(QLabel("Defined Vertices:"))
        table_layout.addWidget(self.vertices_table)
        table_layout.addWidget(delete_vertex_button)

        layout.addWidget(table_widget)
        self.tabs.addTab(tab, "1. Vertices")

    def add_vertex(self):
        try:
            x = float(self.vertex_x_input.text())
            y = float(self.vertex_y_input.text())
            z = float(self.vertex_z_input.text())
        except ValueError:
            QMessageBox.warning(self, "Input Error", "Invalid coordinate format. Please enter numbers.")
            return

        vertex_id = self.vertex_id_counter
        self.vertices.append([vertex_id, x, y, z])
        self.vertex_id_counter += 1
        self.update_vertices_table()
        self.vertex_x_input.clear()
        self.vertex_y_input.clear()
        self.vertex_z_input.clear()
        self.statusBar().showMessage(f"Vertex {vertex_id} added.")
        self.edit_vertex_id_input.setMinimum(-1)
        if self.vertices:
             self.edit_vertex_id_input.setMaximum(self.vertices[-1][0])


    def load_vertex_for_editing(self):
        edit_id = self.edit_vertex_id_input.value()
        if edit_id == -1:
            QMessageBox.information(self, "Info", "Select a Vertex ID to load.")
            return

        vertex_to_edit = None
        for v in self.vertices:
            if v[0] == edit_id:
                vertex_to_edit = v
                break

        if vertex_to_edit:
            self.vertex_x_input.setText(str(vertex_to_edit[1]))
            self.vertex_y_input.setText(str(vertex_to_edit[2]))
            self.vertex_z_input.setText(str(vertex_to_edit[3]))
            self.statusBar().showMessage(f"Loaded Vertex ID {edit_id} for editing.")
        else:
            QMessageBox.warning(self, "Error", f"Vertex ID {edit_id} not found.")
            self.vertex_x_input.clear()
            self.vertex_y_input.clear()
            self.vertex_z_input.clear()

    def update_vertex(self):
        edit_id = self.edit_vertex_id_input.value()
        if edit_id == -1:
            QMessageBox.warning(self, "Selection Error", "No vertex ID selected for update.")
            return

        try:
            new_x = float(self.vertex_x_input.text())
            new_y = float(self.vertex_y_input.text())
            new_z = float(self.vertex_z_input.text())
        except ValueError:
            QMessageBox.warning(self, "Input Error", "Invalid coordinate format. Please enter numbers.")
            return

        found = False
        for i, v in enumerate(self.vertices):
            if v[0] == edit_id:
                self.vertices[i] = [edit_id, new_x, new_y, new_z]
                found = True
                break

        if found:
            self.update_vertices_table()
            self.vertex_x_input.clear()
            self.vertex_y_input.clear()
            self.vertex_z_input.clear()
            self.edit_vertex_id_input.setValue(-1) # Reset selection
            self.statusBar().showMessage(f"Vertex ID {edit_id} updated.")
        else:
            QMessageBox.warning(self, "Error", f"Vertex ID {edit_id} not found for update.")


    def delete_vertex(self):
        selected_rows = self.vertices_table.selectionModel().selectedRows()
        if not selected_rows:
            QMessageBox.warning(self, "Selection Error", "No vertex selected for deletion.")
            return

        # Sort rows in descending order to avoid index issues when deleting
        for row_index in sorted([r.row() for r in selected_rows], reverse=True):
            vertex_id_to_delete = int(self.vertices_table.item(row_index, 0).text())

            # Check if vertex is used in any block
            used_in_block = any(vertex_id_to_delete in block_data[1] for block_data in self.blocks)
            if used_in_block:
                QMessageBox.warning(self, "Deletion Error", f"Vertex ID {vertex_id_to_delete} is used in a block and cannot be deleted.")
                continue

            self.vertices = [v for v in self.vertices if v[0] != vertex_id_to_delete]
            self.statusBar().showMessage(f"Vertex ID {vertex_id_to_delete} deleted.")

        self.update_vertices_table()
        if self.vertices:
            self.edit_vertex_id_input.setMaximum(self.vertices[-1][0] if self.vertices else -1)
        else:
            self.edit_vertex_id_input.setMinimum(-1)
            self.edit_vertex_id_input.setMaximum(-1)


    def update_vertices_table(self):
        self.vertices_table.setRowCount(0)
        for v_id, x, y, z in self.vertices:
            row_position = self.vertices_table.rowCount()
            self.vertices_table.insertRow(row_position)
            self.vertices_table.setItem(row_position, 0, QTableWidgetItem(str(v_id)))
            self.vertices_table.setItem(row_position, 1, QTableWidgetItem(str(x)))
            self.vertices_table.setItem(row_position, 2, QTableWidgetItem(str(y)))
            self.vertices_table.setItem(row_position, 3, QTableWidgetItem(str(z)))

    def create_blocks_tab(self):
        tab = QWidget()
        layout = QHBoxLayout(tab)

        # Left side: Input form
        form_layout_widget = QWidget()
        form_layout = QFormLayout(form_layout_widget)
        form_layout_widget.setMaximumWidth(400)

        self.block_vertices_input = QLineEdit()
        self.block_vertices_input.setPlaceholderText("e.g., 0 1 2 3 4 5 6 7 (8 IDs)")
        self.block_cells_input = QLineEdit()
        self.block_cells_input.setPlaceholderText("e.g., 10 10 5 (nx ny nz)")
        self.block_grading_input = QLineEdit()
        self.block_grading_input.setPlaceholderText("e.g., 1 1 1 (gx gy gz)")
        self.block_grading_input.setText("1 1 1") # Default grading

        form_layout.addRow("Vertex IDs (8):", self.block_vertices_input)
        form_layout.addRow("Cells (nx ny nz):", self.block_cells_input)
        form_layout.addRow("Grading (gx gy gz):", self.block_grading_input)

        add_block_button = QPushButton("Add Block")
        add_block_button.clicked.connect(self.add_block)
        form_layout.addRow(add_block_button)
        layout.addWidget(form_layout_widget)

        # Right side: Table of blocks
        table_widget = QWidget()
        table_layout = QVBoxLayout(table_widget)

        self.blocks_table = QTableWidget()
        self.blocks_table.setColumnCount(4)
        self.blocks_table.setHorizontalHeaderLabels(["ID", "Vertex IDs", "Cells", "Grading"])
        self.blocks_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.blocks_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.blocks_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)

        delete_block_button = QPushButton("Delete Selected Block")
        delete_block_button.clicked.connect(self.delete_block)

        table_layout.addWidget(QLabel("Defined Blocks:"))
        table_layout.addWidget(self.blocks_table)
        table_layout.addWidget(delete_block_button)

        layout.addWidget(table_widget)
        self.tabs.addTab(tab, "2. Blocks")

    def add_block(self):
        v_ids_str = self.block_vertices_input.text().split()
        cells_str = self.block_cells_input.text().split()
        grading_str = self.block_grading_input.text().split()

        if len(v_ids_str) != 8:
            QMessageBox.warning(self, "Input Error", "A block requires exactly 8 vertex IDs.")
            return
        if len(cells_str) != 3:
            QMessageBox.warning(self, "Input Error", "Cells require 3 values (nx ny nz).")
            return
        if len(grading_str) != 3:
            QMessageBox.warning(self, "Input Error", "Grading requires 3 values (gx gy gz).")
            return

        try:
            v_ids = [int(vid) for vid in v_ids_str]
            cells = [int(c) for c in cells_str]
            grading = [float(g) for g in grading_str]
        except ValueError:
            QMessageBox.warning(self, "Input Error", "Invalid format for IDs, cells, or grading.")
            return

        # Validate vertex IDs
        defined_vertex_ids = [v[0] for v in self.vertices]
        for vid in v_ids:
            if vid not in defined_vertex_ids:
                QMessageBox.warning(self, "Input Error", f"Vertex ID {vid} is not defined.")
                return

        if any(c <= 0 for c in cells):
            QMessageBox.warning(self, "Input Error", "Cell counts must be positive integers.")
            return

        block_id = self.block_id_counter
        self.blocks.append([block_id, v_ids, tuple(cells), tuple(grading)])
        self.block_id_counter += 1
        self.update_blocks_table()
        self.block_vertices_input.clear()
        self.block_cells_input.clear()
        self.block_grading_input.setText("1 1 1")
        self.statusBar().showMessage(f"Block {block_id} added.")


    def delete_block(self):
        selected_rows = self.blocks_table.selectionModel().selectedRows()
        if not selected_rows:
            QMessageBox.warning(self, "Selection Error", "No block selected for deletion.")
            return

        for row_index in sorted([r.row() for r in selected_rows], reverse=True):
            block_id_to_delete = int(self.blocks_table.item(row_index, 0).text())

            # Check if block is used in any patch
            used_in_patch = any(patch_data[2] == block_id_to_delete for patch_data in self.patches)
            if used_in_patch:
                QMessageBox.warning(self, "Deletion Error", f"Block ID {block_id_to_delete} is used in a patch and cannot be deleted.")
                continue

            self.blocks = [b for b in self.blocks if b[0] != block_id_to_delete]
            self.statusBar().showMessage(f"Block ID {block_id_to_delete} deleted.")

        self.update_blocks_table()


    def update_blocks_table(self):
        self.blocks_table.setRowCount(0)
        for b_id, v_ids, cells, grading in self.blocks:
            row_position = self.blocks_table.rowCount()
            self.blocks_table.insertRow(row_position)
            self.blocks_table.setItem(row_position, 0, QTableWidgetItem(str(b_id)))
            self.blocks_table.setItem(row_position, 1, QTableWidgetItem(" ".join(map(str, v_ids))))
            self.blocks_table.setItem(row_position, 2, QTableWidgetItem(" ".join(map(str, cells))))
            self.blocks_table.setItem(row_position, 3, QTableWidgetItem(" ".join(map(str, grading))))

    def create_patches_tab(self):
        tab = QWidget()
        layout = QHBoxLayout(tab)

        # Left side: Input form
        form_layout_widget = QWidget()
        form_layout = QFormLayout(form_layout_widget)
        form_layout_widget.setMaximumWidth(350)

        self.patch_name_input = QLineEdit()
        self.patch_type_combo = QComboBox()
        self.patch_type_combo.addItems(["patch", "wall", "empty", "symmetryPlane", "symmetry", "wedge"])

        self.patch_block_id_combo = QComboBox() # Populate with existing block IDs
        self.patch_block_id_combo.currentIndexChanged.connect(self.update_patch_block_id_status)


        self.patch_face_combo = QComboBox()
        self.patch_face_combo.addItems(["west (x0)", "east (x1)", "south (y0)", "north (y1)", "bottom (z0)", "top (z1)"])

        form_layout.addRow("Patch Name:", self.patch_name_input)
        form_layout.addRow("Patch Type:", self.patch_type_combo)
        form_layout.addRow("Block ID:", self.patch_block_id_combo)
        form_layout.addRow("Face:", self.patch_face_combo)

        add_patch_button = QPushButton("Add Patch")
        add_patch_button.clicked.connect(self.add_patch)
        form_layout.addRow(add_patch_button)
        layout.addWidget(form_layout_widget)

        # Right side: Table of patches
        table_widget = QWidget()
        table_layout = QVBoxLayout(table_widget)

        self.patches_table = QTableWidget()
        self.patches_table.setColumnCount(5)
        self.patches_table.setHorizontalHeaderLabels(["Name", "Type", "Block ID", "Face", "Vertices"])
        self.patches_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.patches_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.patches_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)

        delete_patch_button = QPushButton("Delete Selected Patch")
        delete_patch_button.clicked.connect(self.delete_patch)

        table_layout.addWidget(QLabel("Defined Patches:"))
        table_layout.addWidget(self.patches_table)
        table_layout.addWidget(delete_patch_button)

        layout.addWidget(table_widget)
        self.tabs.addTab(tab, "3. Patches")
        self.tabs.currentChanged.connect(self.update_patch_block_id_combo) # Update when tab becomes visible

    def update_patch_block_id_status(self):
        # This is just a placeholder if you want to do something when the combo changes
        # For now, it's mainly populated when the tab is shown
        pass

    def update_patch_block_id_combo(self, index):
        # Update block ID combo only if the Patches tab (index 2) is selected
        if index == 2: # Patches tab
            self.patch_block_id_combo.clear()
            block_ids = [str(b[0]) for b in self.blocks]
            if not block_ids:
                self.patch_block_id_combo.addItem("No blocks defined")
                self.patch_block_id_combo.setEnabled(False)
            else:
                self.patch_block_id_combo.addItems(block_ids)
                self.patch_block_id_combo.setEnabled(True)


    def add_patch(self):
        name = self.patch_name_input.text().strip()
        patch_type = self.patch_type_combo.currentText()

        if not self.blocks:
            QMessageBox.warning(self, "Input Error", "No blocks defined to assign a patch to.")
            return

        if self.patch_block_id_combo.currentIndex() == -1 or self.patch_block_id_combo.currentText() == "No blocks defined":
             QMessageBox.warning(self, "Input Error", "Please select a valid Block ID.")
             return

        try:
            block_id = int(self.patch_block_id_combo.currentText())
        except ValueError:
            QMessageBox.warning(self, "Input Error", "Invalid Block ID selected.")
            return

        face_label_full = self.patch_face_combo.currentText()
        face_label = face_label_full.split(" ")[0] # "west", "east", etc.

        if not name:
            QMessageBox.warning(self, "Input Error", "Patch name cannot be empty.")
            return

        # Find the block and its vertices
        target_block_data = next((b for b in self.blocks if b[0] == block_id), None)
        if not target_block_data:
            QMessageBox.warning(self, "Input Error", f"Block ID {block_id} not found.")
            return

        block_global_v_ids = target_block_data[1]

        # Local vertex indices for faces of a hex block
        # (Order for OpenFOAM: right-hand rule, normal pointing outwards)
        face_local_indices = {
            "west":   [0, 4, 7, 3],
            "east":   [1, 2, 6, 5],
            "south":  [0, 1, 5, 4],
            "north":  [3, 7, 6, 2], # Corrected from some online sources, OpenFOAM standard
            "bottom": [0, 3, 2, 1],
            "top":    [4, 5, 6, 7]
        }

        if face_label not in face_local_indices:
            QMessageBox.critical(self, "Internal Error", f"Unknown face label: {face_label}")
            return

        local_v = face_local_indices[face_label]
        # Map local block vertex indices to global vertex IDs
        face_global_v_ids = [block_global_v_ids[i] for i in local_v]

        self.patches.append([name, patch_type, block_id, face_label_full, face_global_v_ids])
        self.update_patches_table()
        self.patch_name_input.clear()
        self.statusBar().showMessage(f"Patch '{name}' added to block {block_id}, face {face_label}.")

    def delete_patch(self):
        selected_rows = self.patches_table.selectionModel().selectedRows()
        if not selected_rows:
            QMessageBox.warning(self, "Selection Error", "No patch selected for deletion.")
            return

        # Patches are identified by a combination of name, block_id, and face for deletion
        # as names are not unique across the entire patch list in OpenFOAM but within a boundary entry.
        # For simplicity in the GUI, we delete by row.

        indices_to_delete = sorted([r.row() for r in selected_rows], reverse=True)
        for row_index in indices_to_delete:
            deleted_patch_name = self.patches_table.item(row_index, 0).text()
            del self.patches[row_index] # Simple deletion by list index
            self.statusBar().showMessage(f"Patch '{deleted_patch_name}' (row {row_index+1}) deleted.")

        self.update_patches_table()


    def update_patches_table(self):
        self.patches_table.setRowCount(0)
        for name, p_type, b_id, face_lbl, face_v_ids in self.patches:
            row_position = self.patches_table.rowCount()
            self.patches_table.insertRow(row_position)
            self.patches_table.setItem(row_position, 0, QTableWidgetItem(name))
            self.patches_table.setItem(row_position, 1, QTableWidgetItem(p_type))
            self.patches_table.setItem(row_position, 2, QTableWidgetItem(str(b_id)))
            self.patches_table.setItem(row_position, 3, QTableWidgetItem(face_lbl))
            self.patches_table.setItem(row_position, 4, QTableWidgetItem(" ".join(map(str, face_v_ids))))


    def create_generate_tab(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)

        self.blockmesh_dict_preview = QTextEdit()
        self.blockmesh_dict_preview.setReadOnly(True)
        self.blockmesh_dict_preview.setFontFamily("monospace")

        generate_button = QPushButton("Generate blockMeshDict")
        generate_button.clicked.connect(self.generate_blockmesh_dict)

        save_button = QPushButton("Save blockMeshDict to File...")
        save_button.clicked.connect(self.save_blockmesh_dict_to_file)

        layout.addWidget(QLabel("blockMeshDict Preview:"))
        layout.addWidget(self.blockmesh_dict_preview)
        layout.addWidget(generate_button)
        layout.addWidget(save_button)

        self.tabs.addTab(tab, "4. Generate")

    def generate_blockmesh_dict(self):
        if not self.vertices:
            QMessageBox.warning(self, "Generation Error", "No vertices defined.")
            self.blockmesh_dict_preview.setText("")
            return
        if not self.blocks:
            QMessageBox.warning(self, "Generation Error", "No blocks defined.")
            self.blockmesh_dict_preview.setText("")
            return

        # Header
        content = []
        content.append("/*--------------------------------*- C++ -*----------------------------------*\\")
        content.append("| =========                 |                                                 |")
        content.append("| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |")
        content.append("|  \\\\    /   O peration     | Version:  v2312                                 |")
        content.append("|   \\\\  /    A nd           | Website:  www.OpenFOAM.com                      |")
        content.append("|    \\\\/     M anipulation  |                                                 |")
        content.append("\\*---------------------------------------------------------------------------*/")
        content.append("FoamFile")
        content.append("{")
        content.append("    version     2.0;")
        content.append("    format      ascii;")
        content.append("    class       dictionary;")
        content.append("    object      blockMeshDict;")
        content.append("}")
        content.append("// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //")
        content.append("")
        content.append("convertToMeters 1;") # TODO: Make this configurable
        content.append("")

        # Vertices
        content.append("vertices")
        content.append("(")
        # Sort vertices by ID for consistent output, though OpenFOAM doesn't strictly require it if IDs match array index
        sorted_vertices = sorted(self.vertices, key=lambda v: v[0])
        max_vertex_id = -1
        if sorted_vertices:
            max_vertex_id = sorted_vertices[-1][0]

        # Create a list of vertex coordinates, filling in gaps if any (though our GUI ensures contiguous IDs for now)
        vertex_coords_map = {v[0]: (v[1], v[2], v[3]) for v in sorted_vertices}
        for i in range(max_vertex_id + 1):
            if i in vertex_coords_map:
                x, y, z = vertex_coords_map[i]
                content.append(f"    ({x:.6f} {y:.6f} {z:.6f}) // {i}")
            else: # Should not happen with current GUI logic but good for robustness
                content.append(f"    (0 0 0) // Placeholder for missing vertex {i} - ERROR")


        content.append(");")
        content.append("")

        # Blocks
        content.append("blocks")
        content.append("(")
        for b_id, v_ids, cells, grading in self.blocks:
            v_ids_str = " ".join(map(str, v_ids))
            cells_str = " ".join(map(str, cells))
            grading_str = " ".join(map(str, grading))
            content.append(f"    hex ({v_ids_str}) ({cells_str}) simpleGrading ({grading_str}) // block {b_id}")
        content.append(");")
        content.append("")

        # Edges (empty for now)
        content.append("edges")
        content.append("(")
        content.append(");")
        content.append("")

        # Boundary
        content.append("boundary")
        content.append("(")
        # Group patches by name
        patches_by_name = {}
        for name, p_type, b_id, face_lbl, face_v_ids in self.patches:
            if name not in patches_by_name:
                patches_by_name[name] = {"type": p_type, "faces": []}
            # Ensure type consistency for same patch name
            elif patches_by_name[name]["type"] != p_type:
                 QMessageBox.warning(self, "Patch Warning", f"Patch '{name}' has inconsistent types defined. Using first encountered: '{patches_by_name[name]['type']}'.")

            face_v_ids_str = " ".join(map(str, face_v_ids))
            patches_by_name[name]["faces"].append(f"({face_v_ids_str}) // block {b_id} {face_lbl}")

        for name, data in patches_by_name.items():
            content.append(f"    {name}")
            content.append("    {")
            content.append(f"        type        {data['type']};")
            content.append("        faces")
            content.append("        (")
            for face_entry in data["faces"]:
                content.append(f"            {face_entry}")
            content.append("        );")
            content.append("    }")
        content.append(");")
        content.append("")

        # MergePatchPairs (empty for now)
        content.append("mergePatchPairs")
        content.append("(")
        content.append(");")
        content.append("")
        content.append("// ************************************************************************* //")

        self.blockmesh_dict_preview.setText("\n".join(content))
        self.statusBar().showMessage("blockMeshDict generated.")
        self.tabs.setCurrentIndex(3) # Switch to generate tab

    def save_blockmesh_dict_to_file(self):
        content = self.blockmesh_dict_preview.toPlainText()
        if not content:
            QMessageBox.warning(self, "Save Error", "No blockMeshDict content to save. Please generate it first.")
            return

        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Save blockMeshDict",
            "blockMeshDict",  # Default filename
            "All Files (*);;OpenFOAM Dictionary Files (blockMeshDict*)"
        )

        if file_path:
            try:
                with open(file_path, 'w') as f:
                    f.write(content)
                self.statusBar().showMessage(f"blockMeshDict saved to {file_path}")
            except Exception as e:
                QMessageBox.critical(self, "Save Error", f"Could not save file: {e}")
                self.statusBar().showMessage(f"Error saving file: {e}")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # Apply a simple stylesheet for a slightly more "technical" look
    app.setStyleSheet("""
        QWidget {
            font-size: 10pt;
        }
        QPushButton {
            padding: 6px;
            background-color: #e0e0e0;
            border: 1px solid #c0c0c0;
            border-radius: 3px;
        }
        QPushButton:hover {
            background-color: #d0d0d0;
        }
        QPushButton:pressed {
            background-color: #c0c0c0;
        }
        QLineEdit, QSpinBox, QComboBox {
            padding: 4px;
            border: 1px solid #c0c0c0;
            border-radius: 3px;
        }
        QTableWidget {
            gridline-color: #d0d0d0;
        }
        QHeaderView::section {
            background-color: #f0f0f0;
            padding: 4px;
            border: 1px solid #d0d0d0;
        }
        QTabWidget::pane {
            border-top: 2px solid #c0c0c0;
        }
        QTabBar::tab {
            background: #e0e0e0;
            border: 1px solid #c0c0c0;
            border-bottom-color: #c0c0c0; /* same as pane border color */
            border-top-left-radius: 4px;
            border-top-right-radius: 4px;
            min-width: 8ex;
            padding: 5px 10px;
        }
        QTabBar::tab:selected {
            background: #f0f0f0; /* Lighter background for selected tab */
            margin-bottom: -1px; /* make selected tab look connected to pane */
        }
        QTabBar::tab:!selected:hover {
            background: #d5d5d5;
        }
        QTextEdit {
             border: 1px solid #c0c0c0;
        }
    """)
    main_window = BlockMeshApp()
    main_window.show()
    sys.exit(app.exec())