C==========================================================
C     bound.inc  -  boundary data arrays
C==========================================================
      COMMON /BNDC/ IJI(NINA),IJPI(NINA),IJI1(NINA),IJI2(NINA),
     *  FMI(NINA),
     *  IJO(NOUT1),IJPO(NOUT1),IJO1(NOUT1),IJO2(NOUT1),FMO(NOUT1),
     *  IJW(NWT),IJPW(NWT),IJW1(NWT),IJW2(NWT),
     *  IJS(NST),IJPS(NST),IJS1(NST),IJS2(NST),
     *  IJL(NOCT),IJR(NOCT),IJOC1(NOCT),IJOC2(NOCT),
     *  YPL(NWT),VISW(NWT),DN(NWT),FMOC(NOCT)
