C==========================================================
C     indexc.inc  -  grid index common block
C==========================================================
      COMMON /INDXC/ NI,NJ,NIM,NJM,NIJ,IST,JST,
     *  NIGR(NGR),NJGR(NGR),IGR(NGR),JGR(NGR),IJGR(NGR),
     *  NINL(NGR),IIS(NGR),NOUT(NGR),IOS(NGR),
     *  NWAL(NGR),IWS(NGR),NWALI(NGR),NWALA(NGR),IWAS(NGR),
     *  NSYM(NGR),ISS(NGR),NOC(NGR),IOCS(NGR),
     *  LI(NXA),ITB(2,NXA),JTB(2,NYA),
     *  LSG(NGR)
