C==========================================================
C     param.inc  -  CAFFA v2.0 parameter declarations
C==========================================================
      INTEGER NXYA,NXA,NYA,NGR,NFI,MNG
      INTEGER NWT,NST,NOCT,NINA,NOUT1,NKRYL
      PARAMETER (NXYA  = 50000)
      PARAMETER (NXA   = 500,  NYA   = 300)
      PARAMETER (NGR   = 3,    MNG   = 3)
      PARAMETER (NFI   = 11)
      PARAMETER (NWT   = 3000, NST   = 1500)
      PARAMETER (NOCT  = 500,  NINA  = 1500, NOUT1 = 1000)
      PARAMETER (NKRYL = 50)
