      INTEGER         ITE,IED,IVIS
      REAL*8          TE,ED,TEO,EDO
     *               ,TEOO,EDOO,GEN
     *               ,SIJMOD,DOMEGA,FSST
     *               ,OMIJMOD,Q
     *               ,DN,YPL,VISW
     *               ,DCOEF,TEIN,EDIN,SIGT,SIGTE,SIGED
     *               ,CAPPA,CTRANS,ELOG,CMU,CMU25
     *               ,ALPHA,BETTA
     *               ,SIGMK1,SIGMK2,SIGMOM1,SIGMOM2
     *               ,BETAI1,BETAI2,ALPHA1,ALPHA2,A1


      COMMON /VARTUR/ TE(NXYA),ED(NXYA),TEO(NXYA),EDO(NXYA)
     *               ,TEOO(NXYA),EDOO(NXYA),GEN(NXYA)
     *               ,SIJMOD(NXYA),DOMEGA(NXYA),FSST(NXYA)
     *               ,OMIJMOD(NXYA),Q(NXYA)
     *               ,DN(NWA),YPL(NWA),VISW(NWA)
     *               ,DCOEF,TEIN,EDIN,SIGT,SIGTE,SIGED,ITE,IED,IVIS
     *               ,CAPPA,CTRANS,ELOG,CMU,CMU25
     *               ,ALPHA,BETTA
     *               ,SIGMK1,SIGMK2,SIGMOM1,SIGMOM2
     *               ,BETAI1,BETAI2,ALPHA1,ALPHA2,A1
